package com.rubberjam.protobuf.compiler;

import org.junit.Test;

public class ComprehensiveTestNestedParityTest extends AbstractProtoParityTest
{
	@Test
	public void testParity() throws Exception
	{
		// DEBUG: Inspect descriptor
		try {
			// We can't easily load the class here because it is not on the classpath yet?
			// The tests run against the classes generated by protoc in previous steps?
			// Actually, AbstractProtoParityTest generates the code dynamically.
			// But the expected output comes from somewhere.
			// Let's just rely on verifyParity to run our generator, which has debug prints.
		} catch (Exception e) {
			e.printStackTrace();
		}
		verifyParity("comprehensive_test_nested.proto", "ComprehensiveTestNested.java");
	}
}
