// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: comprehensive_test_v3_minimal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ComprehensiveTest.V3Minimmal {

  /// <summary>Holder for reflection information generated from comprehensive_test_v3_minimal.proto</summary>
  public static partial class ComprehensiveTestV3MinimalReflection {

    #region Descriptor
    /// <summary>File descriptor for comprehensive_test_v3_minimal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ComprehensiveTestV3MinimalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNjb21wcmVoZW5zaXZlX3Rlc3RfdjNfbWluaW1hbC5wcm90bxIcQ29tcHJl",
            "aGVuc2l2ZVRlc3QuVjNNaW5pbW1hbCKbBQoPQWxsRmllbGRUeXBlc1YzEhMK",
            "C2ludDMyX2ZpZWxkGAEgASgFEhMKC2ludDY0X2ZpZWxkGAIgASgDEhQKDHVp",
            "bnQzMl9maWVsZBgDIAEoDRIUCgx1aW50NjRfZmllbGQYBCABKAQSFAoMc2lu",
            "dDMyX2ZpZWxkGAUgASgREhQKDHNpbnQ2NF9maWVsZBgGIAEoEhIVCg1maXhl",
            "ZDMyX2ZpZWxkGAcgASgHEhUKDWZpeGVkNjRfZmllbGQYCCABKAYSFgoOc2Zp",
            "eGVkMzJfZmllbGQYCSABKA8SFgoOc2ZpeGVkNjRfZmllbGQYCiABKBASEwoL",
            "ZmxvYXRfZmllbGQYCyABKAISFAoMZG91YmxlX2ZpZWxkGAwgASgBEhIKCmJv",
            "b2xfZmllbGQYDSABKAgSFAoMc3RyaW5nX2ZpZWxkGA4gASgJEhMKC2J5dGVz",
            "X2ZpZWxkGA8gASgMEjwKCmVudW1fZmllbGQYECABKA4yKC5Db21wcmVoZW5z",
            "aXZlVGVzdC5WM01pbmltbWFsLlRlc3RFbnVtVjMSFgoOcmVwZWF0ZWRfaW50",
            "MzIYEiADKAUSFwoPcmVwZWF0ZWRfc3RyaW5nGBMgAygJEj8KDXJlcGVhdGVk",
            "X2VudW0YFCADKA4yKC5Db21wcmVoZW5zaXZlVGVzdC5WM01pbmltbWFsLlRl",
            "c3RFbnVtVjMSHAoPb3B0aW9uYWxfc3RyaW5nGBYgASgJSACIAQESGwoOb3B0",
            "aW9uYWxfaW50MzIYFyABKAVIAYgBARIaCg1vcHRpb25hbF9ib29sGBggASgI",
            "SAKIAQFCEgoQX29wdGlvbmFsX3N0cmluZ0IRCg9fb3B0aW9uYWxfaW50MzJC",
            "EAoOX29wdGlvbmFsX2Jvb2wijgIKD1BhY2tlZE1lc3NhZ2VWMxIYCgxwYWNr",
            "ZWRfaW50MzIYASADKAVCAhABEhgKDHBhY2tlZF9pbnQ2NBgCIAMoA0ICEAES",
            "GQoNcGFja2VkX3VpbnQzMhgDIAMoDUICEAESFwoLcGFja2VkX2Jvb2wYBCAD",
            "KAhCAhABEkEKC3BhY2tlZF9lbnVtGAUgAygOMiguQ29tcHJlaGVuc2l2ZVRl",
            "c3QuVjNNaW5pbW1hbC5UZXN0RW51bVYzQgIQARIaCg5wYWNrZWRfZml4ZWQz",
            "MhgGIAMoB0ICEAESGAoMcGFja2VkX2Zsb2F0GAcgAygCQgIQARIaCg51bnBh",
            "Y2tlZF9pbnQzMhgIIAMoBUICEAAiwQIKDk9uZW9mTWVzc2FnZVYzEhYKDG9u",
            "ZW9mX3N0cmluZxgBIAEoCUgAEhUKC29uZW9mX2ludDMyGAIgASgFSAASPgoK",
            "b25lb2ZfZW51bRgDIAEoDjIoLkNvbXByZWhlbnNpdmVUZXN0LlYzTWluaW1t",
            "YWwuVGVzdEVudW1WM0gAEkYKDW9uZW9mX21lc3NhZ2UYBCABKAsyLS5Db21w",
            "cmVoZW5zaXZlVGVzdC5WM01pbmltbWFsLkFsbEZpZWxkVHlwZXNWM0gAEhUK",
            "C29uZW9mX2J5dGVzGAUgASgMSAASFQoNcmVndWxhcl9maWVsZBgGIAEoCRIU",
            "CgpvbmVvZl9ib29sGAcgASgISAESFgoMb25lb2ZfZG91YmxlGAggASgBSAFC",
            "DAoKdGVzdF9vbmVvZkIOCgxzZWNvbmRfb25lb2YqTwoKVGVzdEVudW1WMxIQ",
            "CgxURVNUX1VOS05PV04QABIOCgpURVNUX0ZJUlNUEAESDwoLVEVTVF9TRUNP",
            "TkQQAhIOCgpURVNUX1RISVJEEANCTQonY29tLnJ1YmJlcmphbS5wcm90b2J1",
            "Zi5jb21waWxlci50ZXN0LnYzQhpDb21wcmVoZW5zaXZlVGVzdFYzTWluaW1h",
            "bEgCgAEAiAEAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ComprehensiveTest.V3Minimmal.TestEnumV3), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3), global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3.Parser, new[]{ "Int32Field", "Int64Field", "Uint32Field", "Uint64Field", "Sint32Field", "Sint64Field", "Fixed32Field", "Fixed64Field", "Sfixed32Field", "Sfixed64Field", "FloatField", "DoubleField", "BoolField", "StringField", "BytesField", "EnumField", "RepeatedInt32", "RepeatedString", "RepeatedEnum", "OptionalString", "OptionalInt32", "OptionalBool" }, new[]{ "OptionalString", "OptionalInt32", "OptionalBool" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.V3Minimmal.PackedMessageV3), global::ComprehensiveTest.V3Minimmal.PackedMessageV3.Parser, new[]{ "PackedInt32", "PackedInt64", "PackedUint32", "PackedBool", "PackedEnum", "PackedFixed32", "PackedFloat", "UnpackedInt32" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.V3Minimmal.OneofMessageV3), global::ComprehensiveTest.V3Minimmal.OneofMessageV3.Parser, new[]{ "OneofString", "OneofInt32", "OneofEnum", "OneofMessage", "OneofBytes", "RegularField", "OneofBool", "OneofDouble" }, new[]{ "TestOneof", "SecondOneof" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Test enum (proto3 - open enum)
  /// </summary>
  public enum TestEnumV3 {
    [pbr::OriginalName("TEST_UNKNOWN")] TestUnknown = 0,
    [pbr::OriginalName("TEST_FIRST")] TestFirst = 1,
    [pbr::OriginalName("TEST_SECOND")] TestSecond = 2,
    /// <summary>
    /// Proto3 enums are open, so unknown values are preserved
    /// </summary>
    [pbr::OriginalName("TEST_THIRD")] TestThird = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Message with all field types (proto3)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AllFieldTypesV3 : pb::IMessage<AllFieldTypesV3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AllFieldTypesV3> _parser = new pb::MessageParser<AllFieldTypesV3>(() => new AllFieldTypesV3());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AllFieldTypesV3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ComprehensiveTest.V3Minimmal.ComprehensiveTestV3MinimalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllFieldTypesV3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllFieldTypesV3(AllFieldTypesV3 other) : this() {
      _hasBits0 = other._hasBits0;
      int32Field_ = other.int32Field_;
      int64Field_ = other.int64Field_;
      uint32Field_ = other.uint32Field_;
      uint64Field_ = other.uint64Field_;
      sint32Field_ = other.sint32Field_;
      sint64Field_ = other.sint64Field_;
      fixed32Field_ = other.fixed32Field_;
      fixed64Field_ = other.fixed64Field_;
      sfixed32Field_ = other.sfixed32Field_;
      sfixed64Field_ = other.sfixed64Field_;
      floatField_ = other.floatField_;
      doubleField_ = other.doubleField_;
      boolField_ = other.boolField_;
      stringField_ = other.stringField_;
      bytesField_ = other.bytesField_;
      enumField_ = other.enumField_;
      repeatedInt32_ = other.repeatedInt32_.Clone();
      repeatedString_ = other.repeatedString_.Clone();
      repeatedEnum_ = other.repeatedEnum_.Clone();
      optionalString_ = other.optionalString_;
      optionalInt32_ = other.optionalInt32_;
      optionalBool_ = other.optionalBool_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllFieldTypesV3 Clone() {
      return new AllFieldTypesV3(this);
    }

    /// <summary>Field number for the "int32_field" field.</summary>
    public const int Int32FieldFieldNumber = 1;
    private int int32Field_;
    /// <summary>
    /// Integer types
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Int32Field {
      get { return int32Field_; }
      set {
        int32Field_ = value;
      }
    }

    /// <summary>Field number for the "int64_field" field.</summary>
    public const int Int64FieldFieldNumber = 2;
    private long int64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Int64Field {
      get { return int64Field_; }
      set {
        int64Field_ = value;
      }
    }

    /// <summary>Field number for the "uint32_field" field.</summary>
    public const int Uint32FieldFieldNumber = 3;
    private uint uint32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uint32Field {
      get { return uint32Field_; }
      set {
        uint32Field_ = value;
      }
    }

    /// <summary>Field number for the "uint64_field" field.</summary>
    public const int Uint64FieldFieldNumber = 4;
    private ulong uint64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uint64Field {
      get { return uint64Field_; }
      set {
        uint64Field_ = value;
      }
    }

    /// <summary>Field number for the "sint32_field" field.</summary>
    public const int Sint32FieldFieldNumber = 5;
    private int sint32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sint32Field {
      get { return sint32Field_; }
      set {
        sint32Field_ = value;
      }
    }

    /// <summary>Field number for the "sint64_field" field.</summary>
    public const int Sint64FieldFieldNumber = 6;
    private long sint64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sint64Field {
      get { return sint64Field_; }
      set {
        sint64Field_ = value;
      }
    }

    /// <summary>Field number for the "fixed32_field" field.</summary>
    public const int Fixed32FieldFieldNumber = 7;
    private uint fixed32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Fixed32Field {
      get { return fixed32Field_; }
      set {
        fixed32Field_ = value;
      }
    }

    /// <summary>Field number for the "fixed64_field" field.</summary>
    public const int Fixed64FieldFieldNumber = 8;
    private ulong fixed64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Fixed64Field {
      get { return fixed64Field_; }
      set {
        fixed64Field_ = value;
      }
    }

    /// <summary>Field number for the "sfixed32_field" field.</summary>
    public const int Sfixed32FieldFieldNumber = 9;
    private int sfixed32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sfixed32Field {
      get { return sfixed32Field_; }
      set {
        sfixed32Field_ = value;
      }
    }

    /// <summary>Field number for the "sfixed64_field" field.</summary>
    public const int Sfixed64FieldFieldNumber = 10;
    private long sfixed64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sfixed64Field {
      get { return sfixed64Field_; }
      set {
        sfixed64Field_ = value;
      }
    }

    /// <summary>Field number for the "float_field" field.</summary>
    public const int FloatFieldFieldNumber = 11;
    private float floatField_;
    /// <summary>
    /// Floating point types
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FloatField {
      get { return floatField_; }
      set {
        floatField_ = value;
      }
    }

    /// <summary>Field number for the "double_field" field.</summary>
    public const int DoubleFieldFieldNumber = 12;
    private double doubleField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DoubleField {
      get { return doubleField_; }
      set {
        doubleField_ = value;
      }
    }

    /// <summary>Field number for the "bool_field" field.</summary>
    public const int BoolFieldFieldNumber = 13;
    private bool boolField_;
    /// <summary>
    /// Other primitive types
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BoolField {
      get { return boolField_; }
      set {
        boolField_ = value;
      }
    }

    /// <summary>Field number for the "string_field" field.</summary>
    public const int StringFieldFieldNumber = 14;
    private string stringField_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringField {
      get { return stringField_; }
      set {
        stringField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bytes_field" field.</summary>
    public const int BytesFieldFieldNumber = 15;
    private pb::ByteString bytesField_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BytesField {
      get { return bytesField_; }
      set {
        bytesField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enum_field" field.</summary>
    public const int EnumFieldFieldNumber = 16;
    private global::ComprehensiveTest.V3Minimmal.TestEnumV3 enumField_ = global::ComprehensiveTest.V3Minimmal.TestEnumV3.TestUnknown;
    /// <summary>
    /// Enum and message types
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ComprehensiveTest.V3Minimmal.TestEnumV3 EnumField {
      get { return enumField_; }
      set {
        enumField_ = value;
      }
    }

    /// <summary>Field number for the "repeated_int32" field.</summary>
    public const int RepeatedInt32FieldNumber = 18;
    private static readonly pb::FieldCodec<int> _repeated_repeatedInt32_codec
        = pb::FieldCodec.ForInt32(146);
    private readonly pbc::RepeatedField<int> repeatedInt32_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// Repeated fields
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> RepeatedInt32 {
      get { return repeatedInt32_; }
    }

    /// <summary>Field number for the "repeated_string" field.</summary>
    public const int RepeatedStringFieldNumber = 19;
    private static readonly pb::FieldCodec<string> _repeated_repeatedString_codec
        = pb::FieldCodec.ForString(154);
    private readonly pbc::RepeatedField<string> repeatedString_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RepeatedString {
      get { return repeatedString_; }
    }

    /// <summary>Field number for the "repeated_enum" field.</summary>
    public const int RepeatedEnumFieldNumber = 20;
    private static readonly pb::FieldCodec<global::ComprehensiveTest.V3Minimmal.TestEnumV3> _repeated_repeatedEnum_codec
        = pb::FieldCodec.ForEnum(162, x => (int) x, x => (global::ComprehensiveTest.V3Minimmal.TestEnumV3) x);
    private readonly pbc::RepeatedField<global::ComprehensiveTest.V3Minimmal.TestEnumV3> repeatedEnum_ = new pbc::RepeatedField<global::ComprehensiveTest.V3Minimmal.TestEnumV3>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ComprehensiveTest.V3Minimmal.TestEnumV3> RepeatedEnum {
      get { return repeatedEnum_; }
    }

    /// <summary>Field number for the "optional_string" field.</summary>
    public const int OptionalStringFieldNumber = 22;
    private readonly static string OptionalStringDefaultValue = "";

    private string optionalString_;
    /// <summary>
    /// Proto3 optional fields (explicit presence)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OptionalString {
      get { return optionalString_ ?? OptionalStringDefaultValue; }
      set {
        optionalString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "optional_string" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOptionalString {
      get { return optionalString_ != null; }
    }
    /// <summary>Clears the value of the "optional_string" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOptionalString() {
      optionalString_ = null;
    }

    /// <summary>Field number for the "optional_int32" field.</summary>
    public const int OptionalInt32FieldNumber = 23;
    private readonly static int OptionalInt32DefaultValue = 0;

    private int optionalInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OptionalInt32 {
      get { if ((_hasBits0 & 1) != 0) { return optionalInt32_; } else { return OptionalInt32DefaultValue; } }
      set {
        _hasBits0 |= 1;
        optionalInt32_ = value;
      }
    }
    /// <summary>Gets whether the "optional_int32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOptionalInt32 {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "optional_int32" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOptionalInt32() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "optional_bool" field.</summary>
    public const int OptionalBoolFieldNumber = 24;
    private readonly static bool OptionalBoolDefaultValue = false;

    private bool optionalBool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OptionalBool {
      get { if ((_hasBits0 & 2) != 0) { return optionalBool_; } else { return OptionalBoolDefaultValue; } }
      set {
        _hasBits0 |= 2;
        optionalBool_ = value;
      }
    }
    /// <summary>Gets whether the "optional_bool" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOptionalBool {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "optional_bool" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOptionalBool() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AllFieldTypesV3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AllFieldTypesV3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Int32Field != other.Int32Field) return false;
      if (Int64Field != other.Int64Field) return false;
      if (Uint32Field != other.Uint32Field) return false;
      if (Uint64Field != other.Uint64Field) return false;
      if (Sint32Field != other.Sint32Field) return false;
      if (Sint64Field != other.Sint64Field) return false;
      if (Fixed32Field != other.Fixed32Field) return false;
      if (Fixed64Field != other.Fixed64Field) return false;
      if (Sfixed32Field != other.Sfixed32Field) return false;
      if (Sfixed64Field != other.Sfixed64Field) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatField, other.FloatField)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleField, other.DoubleField)) return false;
      if (BoolField != other.BoolField) return false;
      if (StringField != other.StringField) return false;
      if (BytesField != other.BytesField) return false;
      if (EnumField != other.EnumField) return false;
      if(!repeatedInt32_.Equals(other.repeatedInt32_)) return false;
      if(!repeatedString_.Equals(other.repeatedString_)) return false;
      if(!repeatedEnum_.Equals(other.repeatedEnum_)) return false;
      if (OptionalString != other.OptionalString) return false;
      if (OptionalInt32 != other.OptionalInt32) return false;
      if (OptionalBool != other.OptionalBool) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Int32Field != 0) hash ^= Int32Field.GetHashCode();
      if (Int64Field != 0L) hash ^= Int64Field.GetHashCode();
      if (Uint32Field != 0) hash ^= Uint32Field.GetHashCode();
      if (Uint64Field != 0UL) hash ^= Uint64Field.GetHashCode();
      if (Sint32Field != 0) hash ^= Sint32Field.GetHashCode();
      if (Sint64Field != 0L) hash ^= Sint64Field.GetHashCode();
      if (Fixed32Field != 0) hash ^= Fixed32Field.GetHashCode();
      if (Fixed64Field != 0UL) hash ^= Fixed64Field.GetHashCode();
      if (Sfixed32Field != 0) hash ^= Sfixed32Field.GetHashCode();
      if (Sfixed64Field != 0L) hash ^= Sfixed64Field.GetHashCode();
      if (FloatField != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatField);
      if (DoubleField != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleField);
      if (BoolField != false) hash ^= BoolField.GetHashCode();
      if (StringField.Length != 0) hash ^= StringField.GetHashCode();
      if (BytesField.Length != 0) hash ^= BytesField.GetHashCode();
      if (EnumField != global::ComprehensiveTest.V3Minimmal.TestEnumV3.TestUnknown) hash ^= EnumField.GetHashCode();
      hash ^= repeatedInt32_.GetHashCode();
      hash ^= repeatedString_.GetHashCode();
      hash ^= repeatedEnum_.GetHashCode();
      if (HasOptionalString) hash ^= OptionalString.GetHashCode();
      if (HasOptionalInt32) hash ^= OptionalInt32.GetHashCode();
      if (HasOptionalBool) hash ^= OptionalBool.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Int32Field != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Field);
      }
      if (Int64Field != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Int64Field);
      }
      if (Uint32Field != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Uint32Field);
      }
      if (Uint64Field != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Uint64Field);
      }
      if (Sint32Field != 0) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sint32Field);
      }
      if (Sint64Field != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sint64Field);
      }
      if (Fixed32Field != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Fixed32Field);
      }
      if (Fixed64Field != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(Fixed64Field);
      }
      if (Sfixed32Field != 0) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sfixed32Field);
      }
      if (Sfixed64Field != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sfixed64Field);
      }
      if (FloatField != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(FloatField);
      }
      if (DoubleField != 0D) {
        output.WriteRawTag(97);
        output.WriteDouble(DoubleField);
      }
      if (BoolField != false) {
        output.WriteRawTag(104);
        output.WriteBool(BoolField);
      }
      if (StringField.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(StringField);
      }
      if (BytesField.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(BytesField);
      }
      if (EnumField != global::ComprehensiveTest.V3Minimmal.TestEnumV3.TestUnknown) {
        output.WriteRawTag(128, 1);
        output.WriteEnum((int) EnumField);
      }
      repeatedInt32_.WriteTo(output, _repeated_repeatedInt32_codec);
      repeatedString_.WriteTo(output, _repeated_repeatedString_codec);
      repeatedEnum_.WriteTo(output, _repeated_repeatedEnum_codec);
      if (HasOptionalString) {
        output.WriteRawTag(178, 1);
        output.WriteString(OptionalString);
      }
      if (HasOptionalInt32) {
        output.WriteRawTag(184, 1);
        output.WriteInt32(OptionalInt32);
      }
      if (HasOptionalBool) {
        output.WriteRawTag(192, 1);
        output.WriteBool(OptionalBool);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Int32Field != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Field);
      }
      if (Int64Field != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Int64Field);
      }
      if (Uint32Field != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Uint32Field);
      }
      if (Uint64Field != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Uint64Field);
      }
      if (Sint32Field != 0) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sint32Field);
      }
      if (Sint64Field != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sint64Field);
      }
      if (Fixed32Field != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Fixed32Field);
      }
      if (Fixed64Field != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(Fixed64Field);
      }
      if (Sfixed32Field != 0) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sfixed32Field);
      }
      if (Sfixed64Field != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sfixed64Field);
      }
      if (FloatField != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(FloatField);
      }
      if (DoubleField != 0D) {
        output.WriteRawTag(97);
        output.WriteDouble(DoubleField);
      }
      if (BoolField != false) {
        output.WriteRawTag(104);
        output.WriteBool(BoolField);
      }
      if (StringField.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(StringField);
      }
      if (BytesField.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(BytesField);
      }
      if (EnumField != global::ComprehensiveTest.V3Minimmal.TestEnumV3.TestUnknown) {
        output.WriteRawTag(128, 1);
        output.WriteEnum((int) EnumField);
      }
      repeatedInt32_.WriteTo(ref output, _repeated_repeatedInt32_codec);
      repeatedString_.WriteTo(ref output, _repeated_repeatedString_codec);
      repeatedEnum_.WriteTo(ref output, _repeated_repeatedEnum_codec);
      if (HasOptionalString) {
        output.WriteRawTag(178, 1);
        output.WriteString(OptionalString);
      }
      if (HasOptionalInt32) {
        output.WriteRawTag(184, 1);
        output.WriteInt32(OptionalInt32);
      }
      if (HasOptionalBool) {
        output.WriteRawTag(192, 1);
        output.WriteBool(OptionalBool);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Int32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32Field);
      }
      if (Int64Field != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Field);
      }
      if (Uint32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uint32Field);
      }
      if (Uint64Field != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uint64Field);
      }
      if (Sint32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Sint32Field);
      }
      if (Sint64Field != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Sint64Field);
      }
      if (Fixed32Field != 0) {
        size += 1 + 4;
      }
      if (Fixed64Field != 0UL) {
        size += 1 + 8;
      }
      if (Sfixed32Field != 0) {
        size += 1 + 4;
      }
      if (Sfixed64Field != 0L) {
        size += 1 + 8;
      }
      if (FloatField != 0F) {
        size += 1 + 4;
      }
      if (DoubleField != 0D) {
        size += 1 + 8;
      }
      if (BoolField != false) {
        size += 1 + 1;
      }
      if (StringField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringField);
      }
      if (BytesField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesField);
      }
      if (EnumField != global::ComprehensiveTest.V3Minimmal.TestEnumV3.TestUnknown) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) EnumField);
      }
      size += repeatedInt32_.CalculateSize(_repeated_repeatedInt32_codec);
      size += repeatedString_.CalculateSize(_repeated_repeatedString_codec);
      size += repeatedEnum_.CalculateSize(_repeated_repeatedEnum_codec);
      if (HasOptionalString) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(OptionalString);
      }
      if (HasOptionalInt32) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(OptionalInt32);
      }
      if (HasOptionalBool) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AllFieldTypesV3 other) {
      if (other == null) {
        return;
      }
      if (other.Int32Field != 0) {
        Int32Field = other.Int32Field;
      }
      if (other.Int64Field != 0L) {
        Int64Field = other.Int64Field;
      }
      if (other.Uint32Field != 0) {
        Uint32Field = other.Uint32Field;
      }
      if (other.Uint64Field != 0UL) {
        Uint64Field = other.Uint64Field;
      }
      if (other.Sint32Field != 0) {
        Sint32Field = other.Sint32Field;
      }
      if (other.Sint64Field != 0L) {
        Sint64Field = other.Sint64Field;
      }
      if (other.Fixed32Field != 0) {
        Fixed32Field = other.Fixed32Field;
      }
      if (other.Fixed64Field != 0UL) {
        Fixed64Field = other.Fixed64Field;
      }
      if (other.Sfixed32Field != 0) {
        Sfixed32Field = other.Sfixed32Field;
      }
      if (other.Sfixed64Field != 0L) {
        Sfixed64Field = other.Sfixed64Field;
      }
      if (other.FloatField != 0F) {
        FloatField = other.FloatField;
      }
      if (other.DoubleField != 0D) {
        DoubleField = other.DoubleField;
      }
      if (other.BoolField != false) {
        BoolField = other.BoolField;
      }
      if (other.StringField.Length != 0) {
        StringField = other.StringField;
      }
      if (other.BytesField.Length != 0) {
        BytesField = other.BytesField;
      }
      if (other.EnumField != global::ComprehensiveTest.V3Minimmal.TestEnumV3.TestUnknown) {
        EnumField = other.EnumField;
      }
      repeatedInt32_.Add(other.repeatedInt32_);
      repeatedString_.Add(other.repeatedString_);
      repeatedEnum_.Add(other.repeatedEnum_);
      if (other.HasOptionalString) {
        OptionalString = other.OptionalString;
      }
      if (other.HasOptionalInt32) {
        OptionalInt32 = other.OptionalInt32;
      }
      if (other.HasOptionalBool) {
        OptionalBool = other.OptionalBool;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Int32Field = input.ReadInt32();
            break;
          }
          case 16: {
            Int64Field = input.ReadInt64();
            break;
          }
          case 24: {
            Uint32Field = input.ReadUInt32();
            break;
          }
          case 32: {
            Uint64Field = input.ReadUInt64();
            break;
          }
          case 40: {
            Sint32Field = input.ReadSInt32();
            break;
          }
          case 48: {
            Sint64Field = input.ReadSInt64();
            break;
          }
          case 61: {
            Fixed32Field = input.ReadFixed32();
            break;
          }
          case 65: {
            Fixed64Field = input.ReadFixed64();
            break;
          }
          case 77: {
            Sfixed32Field = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sfixed64Field = input.ReadSFixed64();
            break;
          }
          case 93: {
            FloatField = input.ReadFloat();
            break;
          }
          case 97: {
            DoubleField = input.ReadDouble();
            break;
          }
          case 104: {
            BoolField = input.ReadBool();
            break;
          }
          case 114: {
            StringField = input.ReadString();
            break;
          }
          case 122: {
            BytesField = input.ReadBytes();
            break;
          }
          case 128: {
            EnumField = (global::ComprehensiveTest.V3Minimmal.TestEnumV3) input.ReadEnum();
            break;
          }
          case 146:
          case 144: {
            repeatedInt32_.AddEntriesFrom(input, _repeated_repeatedInt32_codec);
            break;
          }
          case 154: {
            repeatedString_.AddEntriesFrom(input, _repeated_repeatedString_codec);
            break;
          }
          case 162:
          case 160: {
            repeatedEnum_.AddEntriesFrom(input, _repeated_repeatedEnum_codec);
            break;
          }
          case 178: {
            OptionalString = input.ReadString();
            break;
          }
          case 184: {
            OptionalInt32 = input.ReadInt32();
            break;
          }
          case 192: {
            OptionalBool = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Int32Field = input.ReadInt32();
            break;
          }
          case 16: {
            Int64Field = input.ReadInt64();
            break;
          }
          case 24: {
            Uint32Field = input.ReadUInt32();
            break;
          }
          case 32: {
            Uint64Field = input.ReadUInt64();
            break;
          }
          case 40: {
            Sint32Field = input.ReadSInt32();
            break;
          }
          case 48: {
            Sint64Field = input.ReadSInt64();
            break;
          }
          case 61: {
            Fixed32Field = input.ReadFixed32();
            break;
          }
          case 65: {
            Fixed64Field = input.ReadFixed64();
            break;
          }
          case 77: {
            Sfixed32Field = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sfixed64Field = input.ReadSFixed64();
            break;
          }
          case 93: {
            FloatField = input.ReadFloat();
            break;
          }
          case 97: {
            DoubleField = input.ReadDouble();
            break;
          }
          case 104: {
            BoolField = input.ReadBool();
            break;
          }
          case 114: {
            StringField = input.ReadString();
            break;
          }
          case 122: {
            BytesField = input.ReadBytes();
            break;
          }
          case 128: {
            EnumField = (global::ComprehensiveTest.V3Minimmal.TestEnumV3) input.ReadEnum();
            break;
          }
          case 146:
          case 144: {
            repeatedInt32_.AddEntriesFrom(ref input, _repeated_repeatedInt32_codec);
            break;
          }
          case 154: {
            repeatedString_.AddEntriesFrom(ref input, _repeated_repeatedString_codec);
            break;
          }
          case 162:
          case 160: {
            repeatedEnum_.AddEntriesFrom(ref input, _repeated_repeatedEnum_codec);
            break;
          }
          case 178: {
            OptionalString = input.ReadString();
            break;
          }
          case 184: {
            OptionalInt32 = input.ReadInt32();
            break;
          }
          case 192: {
            OptionalBool = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Message with packed repeated fields (proto3 default)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PackedMessageV3 : pb::IMessage<PackedMessageV3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PackedMessageV3> _parser = new pb::MessageParser<PackedMessageV3>(() => new PackedMessageV3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PackedMessageV3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ComprehensiveTest.V3Minimmal.ComprehensiveTestV3MinimalReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedMessageV3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedMessageV3(PackedMessageV3 other) : this() {
      packedInt32_ = other.packedInt32_.Clone();
      packedInt64_ = other.packedInt64_.Clone();
      packedUint32_ = other.packedUint32_.Clone();
      packedBool_ = other.packedBool_.Clone();
      packedEnum_ = other.packedEnum_.Clone();
      packedFixed32_ = other.packedFixed32_.Clone();
      packedFloat_ = other.packedFloat_.Clone();
      unpackedInt32_ = other.unpackedInt32_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedMessageV3 Clone() {
      return new PackedMessageV3(this);
    }

    /// <summary>Field number for the "packed_int32" field.</summary>
    public const int PackedInt32FieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_packedInt32_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> packedInt32_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PackedInt32 {
      get { return packedInt32_; }
    }

    /// <summary>Field number for the "packed_int64" field.</summary>
    public const int PackedInt64FieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_packedInt64_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> packedInt64_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> PackedInt64 {
      get { return packedInt64_; }
    }

    /// <summary>Field number for the "packed_uint32" field.</summary>
    public const int PackedUint32FieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_packedUint32_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> packedUint32_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> PackedUint32 {
      get { return packedUint32_; }
    }

    /// <summary>Field number for the "packed_bool" field.</summary>
    public const int PackedBoolFieldNumber = 4;
    private static readonly pb::FieldCodec<bool> _repeated_packedBool_codec
        = pb::FieldCodec.ForBool(34);
    private readonly pbc::RepeatedField<bool> packedBool_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<bool> PackedBool {
      get { return packedBool_; }
    }

    /// <summary>Field number for the "packed_enum" field.</summary>
    public const int PackedEnumFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ComprehensiveTest.V3Minimmal.TestEnumV3> _repeated_packedEnum_codec
        = pb::FieldCodec.ForEnum(42, x => (int) x, x => (global::ComprehensiveTest.V3Minimmal.TestEnumV3) x);
    private readonly pbc::RepeatedField<global::ComprehensiveTest.V3Minimmal.TestEnumV3> packedEnum_ = new pbc::RepeatedField<global::ComprehensiveTest.V3Minimmal.TestEnumV3>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ComprehensiveTest.V3Minimmal.TestEnumV3> PackedEnum {
      get { return packedEnum_; }
    }

    /// <summary>Field number for the "packed_fixed32" field.</summary>
    public const int PackedFixed32FieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_packedFixed32_codec
        = pb::FieldCodec.ForFixed32(50);
    private readonly pbc::RepeatedField<uint> packedFixed32_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> PackedFixed32 {
      get { return packedFixed32_; }
    }

    /// <summary>Field number for the "packed_float" field.</summary>
    public const int PackedFloatFieldNumber = 7;
    private static readonly pb::FieldCodec<float> _repeated_packedFloat_codec
        = pb::FieldCodec.ForFloat(58);
    private readonly pbc::RepeatedField<float> packedFloat_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> PackedFloat {
      get { return packedFloat_; }
    }

    /// <summary>Field number for the "unpacked_int32" field.</summary>
    public const int UnpackedInt32FieldNumber = 8;
    private static readonly pb::FieldCodec<int> _repeated_unpackedInt32_codec
        = pb::FieldCodec.ForInt32(64);
    private readonly pbc::RepeatedField<int> unpackedInt32_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// Unpacked (explicit)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> UnpackedInt32 {
      get { return unpackedInt32_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PackedMessageV3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PackedMessageV3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!packedInt32_.Equals(other.packedInt32_)) return false;
      if(!packedInt64_.Equals(other.packedInt64_)) return false;
      if(!packedUint32_.Equals(other.packedUint32_)) return false;
      if(!packedBool_.Equals(other.packedBool_)) return false;
      if(!packedEnum_.Equals(other.packedEnum_)) return false;
      if(!packedFixed32_.Equals(other.packedFixed32_)) return false;
      if(!packedFloat_.Equals(other.packedFloat_)) return false;
      if(!unpackedInt32_.Equals(other.unpackedInt32_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= packedInt32_.GetHashCode();
      hash ^= packedInt64_.GetHashCode();
      hash ^= packedUint32_.GetHashCode();
      hash ^= packedBool_.GetHashCode();
      hash ^= packedEnum_.GetHashCode();
      hash ^= packedFixed32_.GetHashCode();
      hash ^= packedFloat_.GetHashCode();
      hash ^= unpackedInt32_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      packedInt32_.WriteTo(output, _repeated_packedInt32_codec);
      packedInt64_.WriteTo(output, _repeated_packedInt64_codec);
      packedUint32_.WriteTo(output, _repeated_packedUint32_codec);
      packedBool_.WriteTo(output, _repeated_packedBool_codec);
      packedEnum_.WriteTo(output, _repeated_packedEnum_codec);
      packedFixed32_.WriteTo(output, _repeated_packedFixed32_codec);
      packedFloat_.WriteTo(output, _repeated_packedFloat_codec);
      unpackedInt32_.WriteTo(output, _repeated_unpackedInt32_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      packedInt32_.WriteTo(ref output, _repeated_packedInt32_codec);
      packedInt64_.WriteTo(ref output, _repeated_packedInt64_codec);
      packedUint32_.WriteTo(ref output, _repeated_packedUint32_codec);
      packedBool_.WriteTo(ref output, _repeated_packedBool_codec);
      packedEnum_.WriteTo(ref output, _repeated_packedEnum_codec);
      packedFixed32_.WriteTo(ref output, _repeated_packedFixed32_codec);
      packedFloat_.WriteTo(ref output, _repeated_packedFloat_codec);
      unpackedInt32_.WriteTo(ref output, _repeated_unpackedInt32_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += packedInt32_.CalculateSize(_repeated_packedInt32_codec);
      size += packedInt64_.CalculateSize(_repeated_packedInt64_codec);
      size += packedUint32_.CalculateSize(_repeated_packedUint32_codec);
      size += packedBool_.CalculateSize(_repeated_packedBool_codec);
      size += packedEnum_.CalculateSize(_repeated_packedEnum_codec);
      size += packedFixed32_.CalculateSize(_repeated_packedFixed32_codec);
      size += packedFloat_.CalculateSize(_repeated_packedFloat_codec);
      size += unpackedInt32_.CalculateSize(_repeated_unpackedInt32_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PackedMessageV3 other) {
      if (other == null) {
        return;
      }
      packedInt32_.Add(other.packedInt32_);
      packedInt64_.Add(other.packedInt64_);
      packedUint32_.Add(other.packedUint32_);
      packedBool_.Add(other.packedBool_);
      packedEnum_.Add(other.packedEnum_);
      packedFixed32_.Add(other.packedFixed32_);
      packedFloat_.Add(other.packedFloat_);
      unpackedInt32_.Add(other.unpackedInt32_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            packedInt32_.AddEntriesFrom(input, _repeated_packedInt32_codec);
            break;
          }
          case 18:
          case 16: {
            packedInt64_.AddEntriesFrom(input, _repeated_packedInt64_codec);
            break;
          }
          case 26:
          case 24: {
            packedUint32_.AddEntriesFrom(input, _repeated_packedUint32_codec);
            break;
          }
          case 34:
          case 32: {
            packedBool_.AddEntriesFrom(input, _repeated_packedBool_codec);
            break;
          }
          case 42:
          case 40: {
            packedEnum_.AddEntriesFrom(input, _repeated_packedEnum_codec);
            break;
          }
          case 50:
          case 53: {
            packedFixed32_.AddEntriesFrom(input, _repeated_packedFixed32_codec);
            break;
          }
          case 58:
          case 61: {
            packedFloat_.AddEntriesFrom(input, _repeated_packedFloat_codec);
            break;
          }
          case 66:
          case 64: {
            unpackedInt32_.AddEntriesFrom(input, _repeated_unpackedInt32_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            packedInt32_.AddEntriesFrom(ref input, _repeated_packedInt32_codec);
            break;
          }
          case 18:
          case 16: {
            packedInt64_.AddEntriesFrom(ref input, _repeated_packedInt64_codec);
            break;
          }
          case 26:
          case 24: {
            packedUint32_.AddEntriesFrom(ref input, _repeated_packedUint32_codec);
            break;
          }
          case 34:
          case 32: {
            packedBool_.AddEntriesFrom(ref input, _repeated_packedBool_codec);
            break;
          }
          case 42:
          case 40: {
            packedEnum_.AddEntriesFrom(ref input, _repeated_packedEnum_codec);
            break;
          }
          case 50:
          case 53: {
            packedFixed32_.AddEntriesFrom(ref input, _repeated_packedFixed32_codec);
            break;
          }
          case 58:
          case 61: {
            packedFloat_.AddEntriesFrom(ref input, _repeated_packedFloat_codec);
            break;
          }
          case 66:
          case 64: {
            unpackedInt32_.AddEntriesFrom(ref input, _repeated_unpackedInt32_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Message with oneof (proto3)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OneofMessageV3 : pb::IMessage<OneofMessageV3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OneofMessageV3> _parser = new pb::MessageParser<OneofMessageV3>(() => new OneofMessageV3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OneofMessageV3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ComprehensiveTest.V3Minimmal.ComprehensiveTestV3MinimalReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofMessageV3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofMessageV3(OneofMessageV3 other) : this() {
      regularField_ = other.regularField_;
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.OneofString:
          OneofString = other.OneofString;
          break;
        case TestOneofOneofCase.OneofInt32:
          OneofInt32 = other.OneofInt32;
          break;
        case TestOneofOneofCase.OneofEnum:
          OneofEnum = other.OneofEnum;
          break;
        case TestOneofOneofCase.OneofMessage:
          OneofMessage = other.OneofMessage.Clone();
          break;
        case TestOneofOneofCase.OneofBytes:
          OneofBytes = other.OneofBytes;
          break;
      }

      switch (other.SecondOneofCase) {
        case SecondOneofOneofCase.OneofBool:
          OneofBool = other.OneofBool;
          break;
        case SecondOneofOneofCase.OneofDouble:
          OneofDouble = other.OneofDouble;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofMessageV3 Clone() {
      return new OneofMessageV3(this);
    }

    /// <summary>Field number for the "oneof_string" field.</summary>
    public const int OneofStringFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OneofString {
      get { return HasOneofString ? (string) testOneof_ : ""; }
      set {
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.OneofString;
      }
    }
    /// <summary>Gets whether the "oneof_string" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofString {
      get { return testOneofCase_ == TestOneofOneofCase.OneofString; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_string" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofString() {
      if (HasOneofString) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "oneof_int32" field.</summary>
    public const int OneofInt32FieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OneofInt32 {
      get { return HasOneofInt32 ? (int) testOneof_ : 0; }
      set {
        testOneof_ = value;
        testOneofCase_ = TestOneofOneofCase.OneofInt32;
      }
    }
    /// <summary>Gets whether the "oneof_int32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofInt32 {
      get { return testOneofCase_ == TestOneofOneofCase.OneofInt32; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_int32" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofInt32() {
      if (HasOneofInt32) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "oneof_enum" field.</summary>
    public const int OneofEnumFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ComprehensiveTest.V3Minimmal.TestEnumV3 OneofEnum {
      get { return HasOneofEnum ? (global::ComprehensiveTest.V3Minimmal.TestEnumV3) testOneof_ : global::ComprehensiveTest.V3Minimmal.TestEnumV3.TestUnknown; }
      set {
        testOneof_ = value;
        testOneofCase_ = TestOneofOneofCase.OneofEnum;
      }
    }
    /// <summary>Gets whether the "oneof_enum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofEnum {
      get { return testOneofCase_ == TestOneofOneofCase.OneofEnum; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_enum" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofEnum() {
      if (HasOneofEnum) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "oneof_message" field.</summary>
    public const int OneofMessageFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3 OneofMessage {
      get { return testOneofCase_ == TestOneofOneofCase.OneofMessage ? (global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3) testOneof_ : null; }
      set {
        testOneof_ = value;
        testOneofCase_ = value == null ? TestOneofOneofCase.None : TestOneofOneofCase.OneofMessage;
      }
    }

    /// <summary>Field number for the "oneof_bytes" field.</summary>
    public const int OneofBytesFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString OneofBytes {
      get { return HasOneofBytes ? (pb::ByteString) testOneof_ : pb::ByteString.Empty; }
      set {
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.OneofBytes;
      }
    }
    /// <summary>Gets whether the "oneof_bytes" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofBytes {
      get { return testOneofCase_ == TestOneofOneofCase.OneofBytes; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_bytes" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofBytes() {
      if (HasOneofBytes) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "regular_field" field.</summary>
    public const int RegularFieldFieldNumber = 6;
    private string regularField_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RegularField {
      get { return regularField_; }
      set {
        regularField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oneof_bool" field.</summary>
    public const int OneofBoolFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OneofBool {
      get { return HasOneofBool ? (bool) secondOneof_ : false; }
      set {
        secondOneof_ = value;
        secondOneofCase_ = SecondOneofOneofCase.OneofBool;
      }
    }
    /// <summary>Gets whether the "oneof_bool" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofBool {
      get { return secondOneofCase_ == SecondOneofOneofCase.OneofBool; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_bool" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofBool() {
      if (HasOneofBool) {
        ClearSecondOneof();
      }
    }

    /// <summary>Field number for the "oneof_double" field.</summary>
    public const int OneofDoubleFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double OneofDouble {
      get { return HasOneofDouble ? (double) secondOneof_ : 0D; }
      set {
        secondOneof_ = value;
        secondOneofCase_ = SecondOneofOneofCase.OneofDouble;
      }
    }
    /// <summary>Gets whether the "oneof_double" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofDouble {
      get { return secondOneofCase_ == SecondOneofOneofCase.OneofDouble; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_double" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofDouble() {
      if (HasOneofDouble) {
        ClearSecondOneof();
      }
    }

    private object testOneof_;
    /// <summary>Enum of possible cases for the "test_oneof" oneof.</summary>
    public enum TestOneofOneofCase {
      None = 0,
      OneofString = 1,
      OneofInt32 = 2,
      OneofEnum = 3,
      OneofMessage = 4,
      OneofBytes = 5,
    }
    private TestOneofOneofCase testOneofCase_ = TestOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestOneofOneofCase TestOneofCase {
      get { return testOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTestOneof() {
      testOneofCase_ = TestOneofOneofCase.None;
      testOneof_ = null;
    }

    private object secondOneof_;
    /// <summary>Enum of possible cases for the "second_oneof" oneof.</summary>
    public enum SecondOneofOneofCase {
      None = 0,
      OneofBool = 7,
      OneofDouble = 8,
    }
    private SecondOneofOneofCase secondOneofCase_ = SecondOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecondOneofOneofCase SecondOneofCase {
      get { return secondOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSecondOneof() {
      secondOneofCase_ = SecondOneofOneofCase.None;
      secondOneof_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OneofMessageV3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OneofMessageV3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OneofString != other.OneofString) return false;
      if (OneofInt32 != other.OneofInt32) return false;
      if (OneofEnum != other.OneofEnum) return false;
      if (!object.Equals(OneofMessage, other.OneofMessage)) return false;
      if (OneofBytes != other.OneofBytes) return false;
      if (RegularField != other.RegularField) return false;
      if (OneofBool != other.OneofBool) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(OneofDouble, other.OneofDouble)) return false;
      if (TestOneofCase != other.TestOneofCase) return false;
      if (SecondOneofCase != other.SecondOneofCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOneofString) hash ^= OneofString.GetHashCode();
      if (HasOneofInt32) hash ^= OneofInt32.GetHashCode();
      if (HasOneofEnum) hash ^= OneofEnum.GetHashCode();
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) hash ^= OneofMessage.GetHashCode();
      if (HasOneofBytes) hash ^= OneofBytes.GetHashCode();
      if (RegularField.Length != 0) hash ^= RegularField.GetHashCode();
      if (HasOneofBool) hash ^= OneofBool.GetHashCode();
      if (HasOneofDouble) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(OneofDouble);
      hash ^= (int) testOneofCase_;
      hash ^= (int) secondOneofCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOneofString) {
        output.WriteRawTag(10);
        output.WriteString(OneofString);
      }
      if (HasOneofInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(OneofInt32);
      }
      if (HasOneofEnum) {
        output.WriteRawTag(24);
        output.WriteEnum((int) OneofEnum);
      }
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
        output.WriteRawTag(34);
        output.WriteMessage(OneofMessage);
      }
      if (HasOneofBytes) {
        output.WriteRawTag(42);
        output.WriteBytes(OneofBytes);
      }
      if (RegularField.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RegularField);
      }
      if (HasOneofBool) {
        output.WriteRawTag(56);
        output.WriteBool(OneofBool);
      }
      if (HasOneofDouble) {
        output.WriteRawTag(65);
        output.WriteDouble(OneofDouble);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOneofString) {
        output.WriteRawTag(10);
        output.WriteString(OneofString);
      }
      if (HasOneofInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(OneofInt32);
      }
      if (HasOneofEnum) {
        output.WriteRawTag(24);
        output.WriteEnum((int) OneofEnum);
      }
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
        output.WriteRawTag(34);
        output.WriteMessage(OneofMessage);
      }
      if (HasOneofBytes) {
        output.WriteRawTag(42);
        output.WriteBytes(OneofBytes);
      }
      if (RegularField.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RegularField);
      }
      if (HasOneofBool) {
        output.WriteRawTag(56);
        output.WriteBool(OneofBool);
      }
      if (HasOneofDouble) {
        output.WriteRawTag(65);
        output.WriteDouble(OneofDouble);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOneofString) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OneofString);
      }
      if (HasOneofInt32) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OneofInt32);
      }
      if (HasOneofEnum) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OneofEnum);
      }
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OneofMessage);
      }
      if (HasOneofBytes) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OneofBytes);
      }
      if (RegularField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RegularField);
      }
      if (HasOneofBool) {
        size += 1 + 1;
      }
      if (HasOneofDouble) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OneofMessageV3 other) {
      if (other == null) {
        return;
      }
      if (other.RegularField.Length != 0) {
        RegularField = other.RegularField;
      }
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.OneofString:
          OneofString = other.OneofString;
          break;
        case TestOneofOneofCase.OneofInt32:
          OneofInt32 = other.OneofInt32;
          break;
        case TestOneofOneofCase.OneofEnum:
          OneofEnum = other.OneofEnum;
          break;
        case TestOneofOneofCase.OneofMessage:
          if (OneofMessage == null) {
            OneofMessage = new global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3();
          }
          OneofMessage.MergeFrom(other.OneofMessage);
          break;
        case TestOneofOneofCase.OneofBytes:
          OneofBytes = other.OneofBytes;
          break;
      }

      switch (other.SecondOneofCase) {
        case SecondOneofOneofCase.OneofBool:
          OneofBool = other.OneofBool;
          break;
        case SecondOneofOneofCase.OneofDouble:
          OneofDouble = other.OneofDouble;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OneofString = input.ReadString();
            break;
          }
          case 16: {
            OneofInt32 = input.ReadInt32();
            break;
          }
          case 24: {
            testOneof_ = input.ReadEnum();
            testOneofCase_ = TestOneofOneofCase.OneofEnum;
            break;
          }
          case 34: {
            global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3 subBuilder = new global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3();
            if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
              subBuilder.MergeFrom(OneofMessage);
            }
            input.ReadMessage(subBuilder);
            OneofMessage = subBuilder;
            break;
          }
          case 42: {
            OneofBytes = input.ReadBytes();
            break;
          }
          case 50: {
            RegularField = input.ReadString();
            break;
          }
          case 56: {
            OneofBool = input.ReadBool();
            break;
          }
          case 65: {
            OneofDouble = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OneofString = input.ReadString();
            break;
          }
          case 16: {
            OneofInt32 = input.ReadInt32();
            break;
          }
          case 24: {
            testOneof_ = input.ReadEnum();
            testOneofCase_ = TestOneofOneofCase.OneofEnum;
            break;
          }
          case 34: {
            global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3 subBuilder = new global::ComprehensiveTest.V3Minimmal.AllFieldTypesV3();
            if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
              subBuilder.MergeFrom(OneofMessage);
            }
            input.ReadMessage(subBuilder);
            OneofMessage = subBuilder;
            break;
          }
          case 42: {
            OneofBytes = input.ReadBytes();
            break;
          }
          case 50: {
            RegularField = input.ReadString();
            break;
          }
          case 56: {
            OneofBool = input.ReadBool();
            break;
          }
          case 65: {
            OneofDouble = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
