// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: comprehensive_test_extensions_lite_runtime.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ComprehensiveTest.ExtensionsLite {

  /// <summary>Holder for reflection information generated from comprehensive_test_extensions_lite_runtime.proto</summary>
  public static partial class ComprehensiveTestExtensionsLiteRuntimeReflection {

    #region Descriptor
    /// <summary>File descriptor for comprehensive_test_extensions_lite_runtime.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ComprehensiveTestExtensionsLiteRuntimeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjBjb21wcmVoZW5zaXZlX3Rlc3RfZXh0ZW5zaW9uc19saXRlX3J1bnRpbWUu",
            "cHJvdG8SIENvbXByZWhlbnNpdmVUZXN0LkV4dGVuc2lvbnNMaXRlIkwKC0Jh",
            "c2VNZXNzYWdlEhIKCmJhc2VfZmllbGQYASABKAkSEgoKYmFzZV9pbnQzMhgC",
            "IAEoBSoFCGQQyAEqBgj0AxDYBCoGCOgHENAPIkAKEEV4dGVuc2lvbk1lc3Nh",
            "Z2USFQoNZXh0X21zZ19maWVsZBgBIAEoCRIVCg1leHRfbXNnX2ludDMyGAIg",
            "ASgFIjIKEUFub3RoZXJFeHRlbmRhYmxlEhUKDWFub3RoZXJfZmllbGQYASAB",
            "KAkqBgjIARCsAiKXAQoMT3V0ZXJNZXNzYWdlGi4KD0lubmVyRXh0ZW5kYWJs",
            "ZRITCgtpbm5lcl9maWVsZBgBIAEoCSoGCKwCEJADMlcKDmlubmVyX2V4dGVu",
            "ZGVkEj4uQ29tcHJlaGVuc2l2ZVRlc3QuRXh0ZW5zaW9uc0xpdGUuT3V0ZXJN",
            "ZXNzYWdlLklubmVyRXh0ZW5kYWJsZRisAiABKAkqOgoIVGVzdEVudW0SDwoL",
            "RVhUX1VOS05PV04QABINCglFWFRfRklSU1QQARIOCgpFWFRfU0VDT05EEAI6",
            "RgoPZXh0ZW5kZWRfc3RyaW5nEi0uQ29tcHJlaGVuc2l2ZVRlc3QuRXh0ZW5z",
            "aW9uc0xpdGUuQmFzZU1lc3NhZ2UYZCABKAk6RQoOZXh0ZW5kZWRfaW50MzIS",
            "LS5Db21wcmVoZW5zaXZlVGVzdC5FeHRlbnNpb25zTGl0ZS5CYXNlTWVzc2Fn",
            "ZRhlIAEoBTpFCg5leHRlbmRlZF9pbnQ2NBItLkNvbXByZWhlbnNpdmVUZXN0",
            "LkV4dGVuc2lvbnNMaXRlLkJhc2VNZXNzYWdlGGYgASgDOkQKDWV4dGVuZGVk",
            "X2Jvb2wSLS5Db21wcmVoZW5zaXZlVGVzdC5FeHRlbnNpb25zTGl0ZS5CYXNl",
            "TWVzc2FnZRhnIAEoCDpFCg5leHRlbmRlZF9ieXRlcxItLkNvbXByZWhlbnNp",
            "dmVUZXN0LkV4dGVuc2lvbnNMaXRlLkJhc2VNZXNzYWdlGGggASgMOkYKD2V4",
            "dGVuZGVkX2RvdWJsZRItLkNvbXByZWhlbnNpdmVUZXN0LkV4dGVuc2lvbnNM",
            "aXRlLkJhc2VNZXNzYWdlGGkgASgBOkUKDmV4dGVuZGVkX2Zsb2F0Ei0uQ29t",
            "cHJlaGVuc2l2ZVRlc3QuRXh0ZW5zaW9uc0xpdGUuQmFzZU1lc3NhZ2UYaiAB",
            "KAI6TwoYZXh0ZW5kZWRfcmVwZWF0ZWRfc3RyaW5nEi0uQ29tcHJlaGVuc2l2",
            "ZVRlc3QuRXh0ZW5zaW9uc0xpdGUuQmFzZU1lc3NhZ2UYayADKAk6TgoXZXh0",
            "ZW5kZWRfcmVwZWF0ZWRfaW50MzISLS5Db21wcmVoZW5zaXZlVGVzdC5FeHRl",
            "bnNpb25zTGl0ZS5CYXNlTWVzc2FnZRhsIAMoBTpwCg1leHRlbmRlZF9lbnVt",
            "Ei0uQ29tcHJlaGVuc2l2ZVRlc3QuRXh0ZW5zaW9uc0xpdGUuQmFzZU1lc3Nh",
            "Z2UYbSABKA4yKi5Db21wcmVoZW5zaXZlVGVzdC5FeHRlbnNpb25zTGl0ZS5U",
            "ZXN0RW51bTp5ChZleHRlbmRlZF9yZXBlYXRlZF9lbnVtEi0uQ29tcHJlaGVu",
            "c2l2ZVRlc3QuRXh0ZW5zaW9uc0xpdGUuQmFzZU1lc3NhZ2UYbiADKA4yKi5D",
            "b21wcmVoZW5zaXZlVGVzdC5FeHRlbnNpb25zTGl0ZS5UZXN0RW51bTp7ChBl",
            "eHRlbmRlZF9tZXNzYWdlEi0uQ29tcHJlaGVuc2l2ZVRlc3QuRXh0ZW5zaW9u",
            "c0xpdGUuQmFzZU1lc3NhZ2UYbyABKAsyMi5Db21wcmVoZW5zaXZlVGVzdC5F",
            "eHRlbnNpb25zTGl0ZS5FeHRlbnNpb25NZXNzYWdlOoQBChlleHRlbmRlZF9y",
            "ZXBlYXRlZF9tZXNzYWdlEi0uQ29tcHJlaGVuc2l2ZVRlc3QuRXh0ZW5zaW9u",
            "c0xpdGUuQmFzZU1lc3NhZ2UYcCADKAsyMi5Db21wcmVoZW5zaXZlVGVzdC5F",
            "eHRlbnNpb25zTGl0ZS5FeHRlbnNpb25NZXNzYWdlOk4KEGFub3RoZXJfZXh0",
            "ZW5kZWQSMy5Db21wcmVoZW5zaXZlVGVzdC5FeHRlbnNpb25zTGl0ZS5Bbm90",
            "aGVyRXh0ZW5kYWJsZRjIASABKAk6UgoUYW5vdGhlcl9leHRlbmRlZF9pbnQS",
            "My5Db21wcmVoZW5zaXZlVGVzdC5FeHRlbnNpb25zTGl0ZS5Bbm90aGVyRXh0",
            "ZW5kYWJsZRjJASABKAU6WwoVZXh0ZW5kZWRfd2l0aF9kZWZhdWx0Ei0uQ29t",
            "cHJlaGVuc2l2ZVRlc3QuRXh0ZW5zaW9uc0xpdGUuQmFzZU1lc3NhZ2UYcSAB",
            "KAk6DWRlZmF1bHRfdmFsdWU6VAoZZXh0ZW5kZWRfaW50X3dpdGhfZGVmYXVs",
            "dBItLkNvbXByZWhlbnNpdmVUZXN0LkV4dGVuc2lvbnNMaXRlLkJhc2VNZXNz",
            "YWdlGHIgASgFOgI0MjpXChpleHRlbmRlZF9ib29sX3dpdGhfZGVmYXVsdBIt",
            "LkNvbXByZWhlbnNpdmVUZXN0LkV4dGVuc2lvbnNMaXRlLkJhc2VNZXNzYWdl",
            "GHMgASgIOgR0cnVlOk8KFGRlcHJlY2F0ZWRfZXh0ZW5zaW9uEi0uQ29tcHJl",
            "aGVuc2l2ZVRlc3QuRXh0ZW5zaW9uc0xpdGUuQmFzZU1lc3NhZ2UYdCABKAlC",
            "AhgBQlcKL2NvbS5ydWJiZXJqYW0ucHJvdG9idWYuY29tcGlsZXIudGVzdC5l",
            "eHRlbnNpb25zQh9Db21wcmVoZW5zaXZlVGVzdEV4dGVuc2lvbnNMaXRlSAOI",
            "AQA="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ComprehensiveTest.ExtensionsLite.TestEnum), }, new pb::Extension[] { ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedString, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedInt32, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedInt64, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedBool, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedBytes, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedDouble, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedFloat, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedRepeatedString, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedRepeatedInt32, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedEnum, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedRepeatedEnum, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedMessage, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedRepeatedMessage, ComprehensiveTestExtensionsLiteRuntimeExtensions.AnotherExtended, ComprehensiveTestExtensionsLiteRuntimeExtensions.AnotherExtendedInt, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedWithDefault, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedIntWithDefault, ComprehensiveTestExtensionsLiteRuntimeExtensions.ExtendedBoolWithDefault, ComprehensiveTestExtensionsLiteRuntimeExtensions.DeprecatedExtension }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.ExtensionsLite.BaseMessage), global::ComprehensiveTest.ExtensionsLite.BaseMessage.Parser, new[]{ "BaseField", "BaseInt32" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.ExtensionsLite.ExtensionMessage), global::ComprehensiveTest.ExtensionsLite.ExtensionMessage.Parser, new[]{ "ExtMsgField", "ExtMsgInt32" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.ExtensionsLite.AnotherExtendable), global::ComprehensiveTest.ExtensionsLite.AnotherExtendable.Parser, new[]{ "AnotherField" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.ExtensionsLite.OuterMessage), global::ComprehensiveTest.ExtensionsLite.OuterMessage.Parser, null, null, null, new pb::Extension[] { global::ComprehensiveTest.ExtensionsLite.OuterMessage.Extensions.InnerExtended }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ComprehensiveTest.ExtensionsLite.OuterMessage.Types.InnerExtendable), global::ComprehensiveTest.ExtensionsLite.OuterMessage.Types.InnerExtendable.Parser, new[]{ "InnerField" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of comprehensive_test_extensions_lite_runtime.proto</summary>
  public static partial class ComprehensiveTestExtensionsLiteRuntimeExtensions {
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string> ExtendedString =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string>(100, pb::FieldCodec.ForString(802, ""));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, int> ExtendedInt32 =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, int>(101, pb::FieldCodec.ForInt32(808, 0));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, long> ExtendedInt64 =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, long>(102, pb::FieldCodec.ForInt64(816, 0L));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, bool> ExtendedBool =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, bool>(103, pb::FieldCodec.ForBool(824, false));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, pb::ByteString> ExtendedBytes =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, pb::ByteString>(104, pb::FieldCodec.ForBytes(834, pb::ByteString.Empty));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, double> ExtendedDouble =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, double>(105, pb::FieldCodec.ForDouble(841, 0D));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, float> ExtendedFloat =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, float>(106, pb::FieldCodec.ForFloat(853, 0F));
    public static readonly pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string> ExtendedRepeatedString =
      new pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string>(107, pb::FieldCodec.ForString(858));
    public static readonly pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, int> ExtendedRepeatedInt32 =
      new pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, int>(108, pb::FieldCodec.ForInt32(864));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.TestEnum> ExtendedEnum =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.TestEnum>(109, pb::FieldCodec.ForEnum(872, x => (int) x, x => (global::ComprehensiveTest.ExtensionsLite.TestEnum) x, global::ComprehensiveTest.ExtensionsLite.TestEnum.ExtUnknown));
    public static readonly pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.TestEnum> ExtendedRepeatedEnum =
      new pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.TestEnum>(110, pb::FieldCodec.ForEnum(880, x => (int) x, x => (global::ComprehensiveTest.ExtensionsLite.TestEnum) x));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.ExtensionMessage> ExtendedMessage =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.ExtensionMessage>(111, pb::FieldCodec.ForMessage(890, global::ComprehensiveTest.ExtensionsLite.ExtensionMessage.Parser));
    public static readonly pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.ExtensionMessage> ExtendedRepeatedMessage =
      new pb::RepeatedExtension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, global::ComprehensiveTest.ExtensionsLite.ExtensionMessage>(112, pb::FieldCodec.ForMessage(898, global::ComprehensiveTest.ExtensionsLite.ExtensionMessage.Parser));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.AnotherExtendable, string> AnotherExtended =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.AnotherExtendable, string>(200, pb::FieldCodec.ForString(1602, ""));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.AnotherExtendable, int> AnotherExtendedInt =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.AnotherExtendable, int>(201, pb::FieldCodec.ForInt32(1608, 0));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string> ExtendedWithDefault =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string>(113, pb::FieldCodec.ForString(906, global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String("ZGVmYXVsdF92YWx1ZQ=="), 0, 13)));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, int> ExtendedIntWithDefault =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, int>(114, pb::FieldCodec.ForInt32(912, 42));
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, bool> ExtendedBoolWithDefault =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, bool>(115, pb::FieldCodec.ForBool(920, true));
    [global::System.ObsoleteAttribute]
    public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string> DeprecatedExtension =
      new pb::Extension<global::ComprehensiveTest.ExtensionsLite.BaseMessage, string>(116, pb::FieldCodec.ForString(930, ""));
  }

  #region Enums
  /// <summary>
  /// Enum for extension testing
  /// </summary>
  public enum TestEnum {
    [pbr::OriginalName("EXT_UNKNOWN")] ExtUnknown = 0,
    [pbr::OriginalName("EXT_FIRST")] ExtFirst = 1,
    [pbr::OriginalName("EXT_SECOND")] ExtSecond = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Base message for extensions
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BaseMessage : pb::IExtendableMessage<BaseMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaseMessage> _parser = new pb::MessageParser<BaseMessage>(() => new BaseMessage());
    private pb::UnknownFieldSet _unknownFields;
    private pb::ExtensionSet<BaseMessage> _extensions;
    private pb::ExtensionSet<BaseMessage> _Extensions { get { return _extensions; } }
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaseMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ComprehensiveTest.ExtensionsLite.ComprehensiveTestExtensionsLiteRuntimeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseMessage(BaseMessage other) : this() {
      _hasBits0 = other._hasBits0;
      baseField_ = other.baseField_;
      baseInt32_ = other.baseInt32_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      _extensions = pb::ExtensionSet.Clone(other._extensions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseMessage Clone() {
      return new BaseMessage(this);
    }

    /// <summary>Field number for the "base_field" field.</summary>
    public const int BaseFieldFieldNumber = 1;
    private readonly static string BaseFieldDefaultValue = "";

    private string baseField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BaseField {
      get { return baseField_ ?? BaseFieldDefaultValue; }
      set {
        baseField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "base_field" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBaseField {
      get { return baseField_ != null; }
    }
    /// <summary>Clears the value of the "base_field" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBaseField() {
      baseField_ = null;
    }

    /// <summary>Field number for the "base_int32" field.</summary>
    public const int BaseInt32FieldNumber = 2;
    private readonly static int BaseInt32DefaultValue = 0;

    private int baseInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BaseInt32 {
      get { if ((_hasBits0 & 1) != 0) { return baseInt32_; } else { return BaseInt32DefaultValue; } }
      set {
        _hasBits0 |= 1;
        baseInt32_ = value;
      }
    }
    /// <summary>Gets whether the "base_int32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBaseInt32 {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "base_int32" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBaseInt32() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaseMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaseMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BaseField != other.BaseField) return false;
      if (BaseInt32 != other.BaseInt32) return false;
      if (!Equals(_extensions, other._extensions)) {
        return false;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBaseField) hash ^= BaseField.GetHashCode();
      if (HasBaseInt32) hash ^= BaseInt32.GetHashCode();
      if (_extensions != null) {
        hash ^= _extensions.GetHashCode();
      }
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBaseField) {
        output.WriteRawTag(10);
        output.WriteString(BaseField);
      }
      if (HasBaseInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(BaseInt32);
      }
      if (_extensions != null) {
        _extensions.WriteTo(output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBaseField) {
        output.WriteRawTag(10);
        output.WriteString(BaseField);
      }
      if (HasBaseInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(BaseInt32);
      }
      if (_extensions != null) {
        _extensions.WriteTo(ref output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasBaseField) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BaseField);
      }
      if (HasBaseInt32) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BaseInt32);
      }
      if (_extensions != null) {
        size += _extensions.CalculateSize();
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaseMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasBaseField) {
        BaseField = other.BaseField;
      }
      if (other.HasBaseInt32) {
        BaseInt32 = other.BaseInt32;
      }
      pb::ExtensionSet.MergeFrom(ref _extensions, other._extensions);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
            break;
          case 10: {
            BaseField = input.ReadString();
            break;
          }
          case 16: {
            BaseInt32 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, ref input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            }
            break;
          case 10: {
            BaseField = input.ReadString();
            break;
          }
          case 16: {
            BaseInt32 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    public TValue GetExtension<TValue>(pb::Extension<BaseMessage, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetExtension<TValue>(pb::RepeatedExtension<BaseMessage, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetOrInitializeExtension<TValue>(pb::RepeatedExtension<BaseMessage, TValue> extension) {
      return pb::ExtensionSet.GetOrInitialize(ref _extensions, extension);
    }
    public void SetExtension<TValue>(pb::Extension<BaseMessage, TValue> extension, TValue value) {
      pb::ExtensionSet.Set(ref _extensions, extension, value);
    }
    public bool HasExtension<TValue>(pb::Extension<BaseMessage, TValue> extension) {
      return pb::ExtensionSet.Has(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::Extension<BaseMessage, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::RepeatedExtension<BaseMessage, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }

  }

  /// <summary>
  /// Message for extension testing
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExtensionMessage : pb::IMessage<ExtensionMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtensionMessage> _parser = new pb::MessageParser<ExtensionMessage>(() => new ExtensionMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtensionMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ComprehensiveTest.ExtensionsLite.ComprehensiveTestExtensionsLiteRuntimeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionMessage(ExtensionMessage other) : this() {
      _hasBits0 = other._hasBits0;
      extMsgField_ = other.extMsgField_;
      extMsgInt32_ = other.extMsgInt32_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionMessage Clone() {
      return new ExtensionMessage(this);
    }

    /// <summary>Field number for the "ext_msg_field" field.</summary>
    public const int ExtMsgFieldFieldNumber = 1;
    private readonly static string ExtMsgFieldDefaultValue = "";

    private string extMsgField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExtMsgField {
      get { return extMsgField_ ?? ExtMsgFieldDefaultValue; }
      set {
        extMsgField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "ext_msg_field" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExtMsgField {
      get { return extMsgField_ != null; }
    }
    /// <summary>Clears the value of the "ext_msg_field" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExtMsgField() {
      extMsgField_ = null;
    }

    /// <summary>Field number for the "ext_msg_int32" field.</summary>
    public const int ExtMsgInt32FieldNumber = 2;
    private readonly static int ExtMsgInt32DefaultValue = 0;

    private int extMsgInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExtMsgInt32 {
      get { if ((_hasBits0 & 1) != 0) { return extMsgInt32_; } else { return ExtMsgInt32DefaultValue; } }
      set {
        _hasBits0 |= 1;
        extMsgInt32_ = value;
      }
    }
    /// <summary>Gets whether the "ext_msg_int32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExtMsgInt32 {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "ext_msg_int32" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExtMsgInt32() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtensionMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtensionMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExtMsgField != other.ExtMsgField) return false;
      if (ExtMsgInt32 != other.ExtMsgInt32) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasExtMsgField) hash ^= ExtMsgField.GetHashCode();
      if (HasExtMsgInt32) hash ^= ExtMsgInt32.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasExtMsgField) {
        output.WriteRawTag(10);
        output.WriteString(ExtMsgField);
      }
      if (HasExtMsgInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(ExtMsgInt32);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasExtMsgField) {
        output.WriteRawTag(10);
        output.WriteString(ExtMsgField);
      }
      if (HasExtMsgInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(ExtMsgInt32);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasExtMsgField) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExtMsgField);
      }
      if (HasExtMsgInt32) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExtMsgInt32);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtensionMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasExtMsgField) {
        ExtMsgField = other.ExtMsgField;
      }
      if (other.HasExtMsgInt32) {
        ExtMsgInt32 = other.ExtMsgInt32;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ExtMsgField = input.ReadString();
            break;
          }
          case 16: {
            ExtMsgInt32 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ExtMsgField = input.ReadString();
            break;
          }
          case 16: {
            ExtMsgInt32 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Another extendable message
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnotherExtendable : pb::IExtendableMessage<AnotherExtendable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnotherExtendable> _parser = new pb::MessageParser<AnotherExtendable>(() => new AnotherExtendable());
    private pb::UnknownFieldSet _unknownFields;
    private pb::ExtensionSet<AnotherExtendable> _extensions;
    private pb::ExtensionSet<AnotherExtendable> _Extensions { get { return _extensions; } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnotherExtendable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ComprehensiveTest.ExtensionsLite.ComprehensiveTestExtensionsLiteRuntimeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnotherExtendable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnotherExtendable(AnotherExtendable other) : this() {
      anotherField_ = other.anotherField_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      _extensions = pb::ExtensionSet.Clone(other._extensions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnotherExtendable Clone() {
      return new AnotherExtendable(this);
    }

    /// <summary>Field number for the "another_field" field.</summary>
    public const int AnotherFieldFieldNumber = 1;
    private readonly static string AnotherFieldDefaultValue = "";

    private string anotherField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AnotherField {
      get { return anotherField_ ?? AnotherFieldDefaultValue; }
      set {
        anotherField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "another_field" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAnotherField {
      get { return anotherField_ != null; }
    }
    /// <summary>Clears the value of the "another_field" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAnotherField() {
      anotherField_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnotherExtendable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnotherExtendable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AnotherField != other.AnotherField) return false;
      if (!Equals(_extensions, other._extensions)) {
        return false;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAnotherField) hash ^= AnotherField.GetHashCode();
      if (_extensions != null) {
        hash ^= _extensions.GetHashCode();
      }
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAnotherField) {
        output.WriteRawTag(10);
        output.WriteString(AnotherField);
      }
      if (_extensions != null) {
        _extensions.WriteTo(output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAnotherField) {
        output.WriteRawTag(10);
        output.WriteString(AnotherField);
      }
      if (_extensions != null) {
        _extensions.WriteTo(ref output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAnotherField) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnotherField);
      }
      if (_extensions != null) {
        size += _extensions.CalculateSize();
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnotherExtendable other) {
      if (other == null) {
        return;
      }
      if (other.HasAnotherField) {
        AnotherField = other.AnotherField;
      }
      pb::ExtensionSet.MergeFrom(ref _extensions, other._extensions);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
            break;
          case 10: {
            AnotherField = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, ref input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            }
            break;
          case 10: {
            AnotherField = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    public TValue GetExtension<TValue>(pb::Extension<AnotherExtendable, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetExtension<TValue>(pb::RepeatedExtension<AnotherExtendable, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetOrInitializeExtension<TValue>(pb::RepeatedExtension<AnotherExtendable, TValue> extension) {
      return pb::ExtensionSet.GetOrInitialize(ref _extensions, extension);
    }
    public void SetExtension<TValue>(pb::Extension<AnotherExtendable, TValue> extension, TValue value) {
      pb::ExtensionSet.Set(ref _extensions, extension, value);
    }
    public bool HasExtension<TValue>(pb::Extension<AnotherExtendable, TValue> extension) {
      return pb::ExtensionSet.Has(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::Extension<AnotherExtendable, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::RepeatedExtension<AnotherExtendable, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }

  }

  /// <summary>
  /// Nested extendable message
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OuterMessage : pb::IMessage<OuterMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OuterMessage> _parser = new pb::MessageParser<OuterMessage>(() => new OuterMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OuterMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ComprehensiveTest.ExtensionsLite.ComprehensiveTestExtensionsLiteRuntimeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OuterMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OuterMessage(OuterMessage other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OuterMessage Clone() {
      return new OuterMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OuterMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OuterMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OuterMessage other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the OuterMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class InnerExtendable : pb::IExtendableMessage<InnerExtendable>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<InnerExtendable> _parser = new pb::MessageParser<InnerExtendable>(() => new InnerExtendable());
        private pb::UnknownFieldSet _unknownFields;
        private pb::ExtensionSet<InnerExtendable> _extensions;
        private pb::ExtensionSet<InnerExtendable> _Extensions { get { return _extensions; } }
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<InnerExtendable> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ComprehensiveTest.ExtensionsLite.OuterMessage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public InnerExtendable() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public InnerExtendable(InnerExtendable other) : this() {
          innerField_ = other.innerField_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          _extensions = pb::ExtensionSet.Clone(other._extensions);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public InnerExtendable Clone() {
          return new InnerExtendable(this);
        }

        /// <summary>Field number for the "inner_field" field.</summary>
        public const int InnerFieldFieldNumber = 1;
        private readonly static string InnerFieldDefaultValue = "";

        private string innerField_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string InnerField {
          get { return innerField_ ?? InnerFieldDefaultValue; }
          set {
            innerField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "inner_field" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasInnerField {
          get { return innerField_ != null; }
        }
        /// <summary>Clears the value of the "inner_field" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearInnerField() {
          innerField_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as InnerExtendable);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(InnerExtendable other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (InnerField != other.InnerField) return false;
          if (!Equals(_extensions, other._extensions)) {
            return false;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasInnerField) hash ^= InnerField.GetHashCode();
          if (_extensions != null) {
            hash ^= _extensions.GetHashCode();
          }
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasInnerField) {
            output.WriteRawTag(10);
            output.WriteString(InnerField);
          }
          if (_extensions != null) {
            _extensions.WriteTo(output);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasInnerField) {
            output.WriteRawTag(10);
            output.WriteString(InnerField);
          }
          if (_extensions != null) {
            _extensions.WriteTo(ref output);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasInnerField) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(InnerField);
          }
          if (_extensions != null) {
            size += _extensions.CalculateSize();
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(InnerExtendable other) {
          if (other == null) {
            return;
          }
          if (other.HasInnerField) {
            InnerField = other.InnerField;
          }
          pb::ExtensionSet.MergeFrom(ref _extensions, other._extensions);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, input)) {
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                }
                break;
              case 10: {
                InnerField = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, ref input)) {
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                }
                break;
              case 10: {
                InnerField = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

        public TValue GetExtension<TValue>(pb::Extension<InnerExtendable, TValue> extension) {
          return pb::ExtensionSet.Get(ref _extensions, extension);
        }
        public pbc::RepeatedField<TValue> GetExtension<TValue>(pb::RepeatedExtension<InnerExtendable, TValue> extension) {
          return pb::ExtensionSet.Get(ref _extensions, extension);
        }
        public pbc::RepeatedField<TValue> GetOrInitializeExtension<TValue>(pb::RepeatedExtension<InnerExtendable, TValue> extension) {
          return pb::ExtensionSet.GetOrInitialize(ref _extensions, extension);
        }
        public void SetExtension<TValue>(pb::Extension<InnerExtendable, TValue> extension, TValue value) {
          pb::ExtensionSet.Set(ref _extensions, extension, value);
        }
        public bool HasExtension<TValue>(pb::Extension<InnerExtendable, TValue> extension) {
          return pb::ExtensionSet.Has(ref _extensions, extension);
        }
        public void ClearExtension<TValue>(pb::Extension<InnerExtendable, TValue> extension) {
          pb::ExtensionSet.Clear(ref _extensions, extension);
        }
        public void ClearExtension<TValue>(pb::RepeatedExtension<InnerExtendable, TValue> extension) {
          pb::ExtensionSet.Clear(ref _extensions, extension);
        }

      }

    }
    #endregion

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the OuterMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::ComprehensiveTest.ExtensionsLite.OuterMessage.Types.InnerExtendable, string> InnerExtended =
        new pb::Extension<global::ComprehensiveTest.ExtensionsLite.OuterMessage.Types.InnerExtendable, string>(300, pb::FieldCodec.ForString(2402, ""));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
