// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: incremental_test_step_2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IncrementalTest.Step2 {

  /// <summary>Holder for reflection information generated from incremental_test_step_2.proto</summary>
  public static partial class IncrementalTestStep2Reflection {

    #region Descriptor
    /// <summary>File descriptor for incremental_test_step_2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IncrementalTestStep2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1pbmNyZW1lbnRhbF90ZXN0X3N0ZXBfMi5wcm90bxIVSW5jcmVtZW50YWxU",
            "ZXN0LlN0ZXAyGhlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvGh9nb29nbGUv",
            "cHJvdG9idWYvdGltZXN0YW1wLnByb3RvGh5nb29nbGUvcHJvdG9idWYvZHVy",
            "YXRpb24ucHJvdG8aHGdvb2dsZS9wcm90b2J1Zi9zdHJ1Y3QucHJvdG8aG2dv",
            "b2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxogZ29vZ2xlL3Byb3RvYnVmL2Zp",
            "ZWxkX21hc2sucHJvdG8i8QEKD0FsbEZpZWxkVHlwZXNWMxITCgtpbnQzMl9m",
            "aWVsZBgBIAEoBRITCgtpbnQ2NF9maWVsZBgCIAEoAxIUCgx1aW50MzJfZmll",
            "bGQYAyABKA0SFAoMdWludDY0X2ZpZWxkGAQgASgEEhQKDHNpbnQzMl9maWVs",
            "ZBgFIAEoERIUCgxzaW50NjRfZmllbGQYBiABKBISFQoNZml4ZWQzMl9maWVs",
            "ZBgHIAEoBxIVCg1maXhlZDY0X2ZpZWxkGAggASgGEhYKDnNmaXhlZDMyX2Zp",
            "ZWxkGAkgASgPEhYKDnNmaXhlZDY0X2ZpZWxkGAogASgQIrMCCg5PbmVvZk1l",
            "c3NhZ2VWMxIWCgxvbmVvZl9zdHJpbmcYASABKAlIABIVCgtvbmVvZl9pbnQz",
            "MhgCIAEoBUgAEjcKCm9uZW9mX2VudW0YAyABKA4yIS5JbmNyZW1lbnRhbFRl",
            "c3QuU3RlcDIuVGVzdEVudW1WM0gAEj8KDW9uZW9mX21lc3NhZ2UYBCABKAsy",
            "Ji5JbmNyZW1lbnRhbFRlc3QuU3RlcDIuQWxsRmllbGRUeXBlc1YzSAASFQoL",
            "b25lb2ZfYnl0ZXMYBSABKAxIABIVCg1yZWd1bGFyX2ZpZWxkGAYgASgJEhQK",
            "Cm9uZW9mX2Jvb2wYByABKAhIARIWCgxvbmVvZl9kb3VibGUYCCABKAFIAUIM",
            "Cgp0ZXN0X29uZW9mQg4KDHNlY29uZF9vbmVvZipPCgpUZXN0RW51bVYzEhAK",
            "DFRFU1RfVU5LTk9XThAAEg4KClRFU1RfRklSU1QQARIPCgtURVNUX1NFQ09O",
            "RBACEg4KClRFU1RfVEhJUkQQA0JQCjBjb20ucnViYmVyamFtLnByb3RvYnVm",
            "LmNvbXBpbGVyLnRlc3QuaW5jcmVtZW50YWxCFEluY3JlbWVudGFsVGVzdFN0",
            "ZXAySAKAAQCIAQBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::IncrementalTest.Step2.TestEnumV3), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IncrementalTest.Step2.AllFieldTypesV3), global::IncrementalTest.Step2.AllFieldTypesV3.Parser, new[]{ "Int32Field", "Int64Field", "Uint32Field", "Uint64Field", "Sint32Field", "Sint64Field", "Fixed32Field", "Fixed64Field", "Sfixed32Field", "Sfixed64Field" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::IncrementalTest.Step2.OneofMessageV3), global::IncrementalTest.Step2.OneofMessageV3.Parser, new[]{ "OneofString", "OneofInt32", "OneofEnum", "OneofMessage", "OneofBytes", "RegularField", "OneofBool", "OneofDouble" }, new[]{ "TestOneof", "SecondOneof" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Test enum (proto3 - open enum)
  /// </summary>
  public enum TestEnumV3 {
    [pbr::OriginalName("TEST_UNKNOWN")] TestUnknown = 0,
    [pbr::OriginalName("TEST_FIRST")] TestFirst = 1,
    [pbr::OriginalName("TEST_SECOND")] TestSecond = 2,
    /// <summary>
    /// Proto3 enums are open, so unknown values are preserved
    /// </summary>
    [pbr::OriginalName("TEST_THIRD")] TestThird = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Message with all field types (proto3)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AllFieldTypesV3 : pb::IMessage<AllFieldTypesV3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AllFieldTypesV3> _parser = new pb::MessageParser<AllFieldTypesV3>(() => new AllFieldTypesV3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AllFieldTypesV3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IncrementalTest.Step2.IncrementalTestStep2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllFieldTypesV3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllFieldTypesV3(AllFieldTypesV3 other) : this() {
      int32Field_ = other.int32Field_;
      int64Field_ = other.int64Field_;
      uint32Field_ = other.uint32Field_;
      uint64Field_ = other.uint64Field_;
      sint32Field_ = other.sint32Field_;
      sint64Field_ = other.sint64Field_;
      fixed32Field_ = other.fixed32Field_;
      fixed64Field_ = other.fixed64Field_;
      sfixed32Field_ = other.sfixed32Field_;
      sfixed64Field_ = other.sfixed64Field_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllFieldTypesV3 Clone() {
      return new AllFieldTypesV3(this);
    }

    /// <summary>Field number for the "int32_field" field.</summary>
    public const int Int32FieldFieldNumber = 1;
    private int int32Field_;
    /// <summary>
    /// Integer types
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Int32Field {
      get { return int32Field_; }
      set {
        int32Field_ = value;
      }
    }

    /// <summary>Field number for the "int64_field" field.</summary>
    public const int Int64FieldFieldNumber = 2;
    private long int64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Int64Field {
      get { return int64Field_; }
      set {
        int64Field_ = value;
      }
    }

    /// <summary>Field number for the "uint32_field" field.</summary>
    public const int Uint32FieldFieldNumber = 3;
    private uint uint32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uint32Field {
      get { return uint32Field_; }
      set {
        uint32Field_ = value;
      }
    }

    /// <summary>Field number for the "uint64_field" field.</summary>
    public const int Uint64FieldFieldNumber = 4;
    private ulong uint64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uint64Field {
      get { return uint64Field_; }
      set {
        uint64Field_ = value;
      }
    }

    /// <summary>Field number for the "sint32_field" field.</summary>
    public const int Sint32FieldFieldNumber = 5;
    private int sint32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sint32Field {
      get { return sint32Field_; }
      set {
        sint32Field_ = value;
      }
    }

    /// <summary>Field number for the "sint64_field" field.</summary>
    public const int Sint64FieldFieldNumber = 6;
    private long sint64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sint64Field {
      get { return sint64Field_; }
      set {
        sint64Field_ = value;
      }
    }

    /// <summary>Field number for the "fixed32_field" field.</summary>
    public const int Fixed32FieldFieldNumber = 7;
    private uint fixed32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Fixed32Field {
      get { return fixed32Field_; }
      set {
        fixed32Field_ = value;
      }
    }

    /// <summary>Field number for the "fixed64_field" field.</summary>
    public const int Fixed64FieldFieldNumber = 8;
    private ulong fixed64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Fixed64Field {
      get { return fixed64Field_; }
      set {
        fixed64Field_ = value;
      }
    }

    /// <summary>Field number for the "sfixed32_field" field.</summary>
    public const int Sfixed32FieldFieldNumber = 9;
    private int sfixed32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sfixed32Field {
      get { return sfixed32Field_; }
      set {
        sfixed32Field_ = value;
      }
    }

    /// <summary>Field number for the "sfixed64_field" field.</summary>
    public const int Sfixed64FieldFieldNumber = 10;
    private long sfixed64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sfixed64Field {
      get { return sfixed64Field_; }
      set {
        sfixed64Field_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AllFieldTypesV3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AllFieldTypesV3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Int32Field != other.Int32Field) return false;
      if (Int64Field != other.Int64Field) return false;
      if (Uint32Field != other.Uint32Field) return false;
      if (Uint64Field != other.Uint64Field) return false;
      if (Sint32Field != other.Sint32Field) return false;
      if (Sint64Field != other.Sint64Field) return false;
      if (Fixed32Field != other.Fixed32Field) return false;
      if (Fixed64Field != other.Fixed64Field) return false;
      if (Sfixed32Field != other.Sfixed32Field) return false;
      if (Sfixed64Field != other.Sfixed64Field) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Int32Field != 0) hash ^= Int32Field.GetHashCode();
      if (Int64Field != 0L) hash ^= Int64Field.GetHashCode();
      if (Uint32Field != 0) hash ^= Uint32Field.GetHashCode();
      if (Uint64Field != 0UL) hash ^= Uint64Field.GetHashCode();
      if (Sint32Field != 0) hash ^= Sint32Field.GetHashCode();
      if (Sint64Field != 0L) hash ^= Sint64Field.GetHashCode();
      if (Fixed32Field != 0) hash ^= Fixed32Field.GetHashCode();
      if (Fixed64Field != 0UL) hash ^= Fixed64Field.GetHashCode();
      if (Sfixed32Field != 0) hash ^= Sfixed32Field.GetHashCode();
      if (Sfixed64Field != 0L) hash ^= Sfixed64Field.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Int32Field != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Field);
      }
      if (Int64Field != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Int64Field);
      }
      if (Uint32Field != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Uint32Field);
      }
      if (Uint64Field != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Uint64Field);
      }
      if (Sint32Field != 0) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sint32Field);
      }
      if (Sint64Field != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sint64Field);
      }
      if (Fixed32Field != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Fixed32Field);
      }
      if (Fixed64Field != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(Fixed64Field);
      }
      if (Sfixed32Field != 0) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sfixed32Field);
      }
      if (Sfixed64Field != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sfixed64Field);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Int32Field != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Field);
      }
      if (Int64Field != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Int64Field);
      }
      if (Uint32Field != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Uint32Field);
      }
      if (Uint64Field != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Uint64Field);
      }
      if (Sint32Field != 0) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sint32Field);
      }
      if (Sint64Field != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sint64Field);
      }
      if (Fixed32Field != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Fixed32Field);
      }
      if (Fixed64Field != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(Fixed64Field);
      }
      if (Sfixed32Field != 0) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sfixed32Field);
      }
      if (Sfixed64Field != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sfixed64Field);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Int32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32Field);
      }
      if (Int64Field != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Field);
      }
      if (Uint32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uint32Field);
      }
      if (Uint64Field != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uint64Field);
      }
      if (Sint32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Sint32Field);
      }
      if (Sint64Field != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Sint64Field);
      }
      if (Fixed32Field != 0) {
        size += 1 + 4;
      }
      if (Fixed64Field != 0UL) {
        size += 1 + 8;
      }
      if (Sfixed32Field != 0) {
        size += 1 + 4;
      }
      if (Sfixed64Field != 0L) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AllFieldTypesV3 other) {
      if (other == null) {
        return;
      }
      if (other.Int32Field != 0) {
        Int32Field = other.Int32Field;
      }
      if (other.Int64Field != 0L) {
        Int64Field = other.Int64Field;
      }
      if (other.Uint32Field != 0) {
        Uint32Field = other.Uint32Field;
      }
      if (other.Uint64Field != 0UL) {
        Uint64Field = other.Uint64Field;
      }
      if (other.Sint32Field != 0) {
        Sint32Field = other.Sint32Field;
      }
      if (other.Sint64Field != 0L) {
        Sint64Field = other.Sint64Field;
      }
      if (other.Fixed32Field != 0) {
        Fixed32Field = other.Fixed32Field;
      }
      if (other.Fixed64Field != 0UL) {
        Fixed64Field = other.Fixed64Field;
      }
      if (other.Sfixed32Field != 0) {
        Sfixed32Field = other.Sfixed32Field;
      }
      if (other.Sfixed64Field != 0L) {
        Sfixed64Field = other.Sfixed64Field;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Int32Field = input.ReadInt32();
            break;
          }
          case 16: {
            Int64Field = input.ReadInt64();
            break;
          }
          case 24: {
            Uint32Field = input.ReadUInt32();
            break;
          }
          case 32: {
            Uint64Field = input.ReadUInt64();
            break;
          }
          case 40: {
            Sint32Field = input.ReadSInt32();
            break;
          }
          case 48: {
            Sint64Field = input.ReadSInt64();
            break;
          }
          case 61: {
            Fixed32Field = input.ReadFixed32();
            break;
          }
          case 65: {
            Fixed64Field = input.ReadFixed64();
            break;
          }
          case 77: {
            Sfixed32Field = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sfixed64Field = input.ReadSFixed64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Int32Field = input.ReadInt32();
            break;
          }
          case 16: {
            Int64Field = input.ReadInt64();
            break;
          }
          case 24: {
            Uint32Field = input.ReadUInt32();
            break;
          }
          case 32: {
            Uint64Field = input.ReadUInt64();
            break;
          }
          case 40: {
            Sint32Field = input.ReadSInt32();
            break;
          }
          case 48: {
            Sint64Field = input.ReadSInt64();
            break;
          }
          case 61: {
            Fixed32Field = input.ReadFixed32();
            break;
          }
          case 65: {
            Fixed64Field = input.ReadFixed64();
            break;
          }
          case 77: {
            Sfixed32Field = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sfixed64Field = input.ReadSFixed64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Message with oneof (proto3)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OneofMessageV3 : pb::IMessage<OneofMessageV3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OneofMessageV3> _parser = new pb::MessageParser<OneofMessageV3>(() => new OneofMessageV3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OneofMessageV3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IncrementalTest.Step2.IncrementalTestStep2Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofMessageV3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofMessageV3(OneofMessageV3 other) : this() {
      regularField_ = other.regularField_;
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.OneofString:
          OneofString = other.OneofString;
          break;
        case TestOneofOneofCase.OneofInt32:
          OneofInt32 = other.OneofInt32;
          break;
        case TestOneofOneofCase.OneofEnum:
          OneofEnum = other.OneofEnum;
          break;
        case TestOneofOneofCase.OneofMessage:
          OneofMessage = other.OneofMessage.Clone();
          break;
        case TestOneofOneofCase.OneofBytes:
          OneofBytes = other.OneofBytes;
          break;
      }

      switch (other.SecondOneofCase) {
        case SecondOneofOneofCase.OneofBool:
          OneofBool = other.OneofBool;
          break;
        case SecondOneofOneofCase.OneofDouble:
          OneofDouble = other.OneofDouble;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofMessageV3 Clone() {
      return new OneofMessageV3(this);
    }

    /// <summary>Field number for the "oneof_string" field.</summary>
    public const int OneofStringFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OneofString {
      get { return HasOneofString ? (string) testOneof_ : ""; }
      set {
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.OneofString;
      }
    }
    /// <summary>Gets whether the "oneof_string" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofString {
      get { return testOneofCase_ == TestOneofOneofCase.OneofString; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_string" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofString() {
      if (HasOneofString) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "oneof_int32" field.</summary>
    public const int OneofInt32FieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OneofInt32 {
      get { return HasOneofInt32 ? (int) testOneof_ : 0; }
      set {
        testOneof_ = value;
        testOneofCase_ = TestOneofOneofCase.OneofInt32;
      }
    }
    /// <summary>Gets whether the "oneof_int32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofInt32 {
      get { return testOneofCase_ == TestOneofOneofCase.OneofInt32; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_int32" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofInt32() {
      if (HasOneofInt32) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "oneof_enum" field.</summary>
    public const int OneofEnumFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IncrementalTest.Step2.TestEnumV3 OneofEnum {
      get { return HasOneofEnum ? (global::IncrementalTest.Step2.TestEnumV3) testOneof_ : global::IncrementalTest.Step2.TestEnumV3.TestUnknown; }
      set {
        testOneof_ = value;
        testOneofCase_ = TestOneofOneofCase.OneofEnum;
      }
    }
    /// <summary>Gets whether the "oneof_enum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofEnum {
      get { return testOneofCase_ == TestOneofOneofCase.OneofEnum; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_enum" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofEnum() {
      if (HasOneofEnum) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "oneof_message" field.</summary>
    public const int OneofMessageFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IncrementalTest.Step2.AllFieldTypesV3 OneofMessage {
      get { return testOneofCase_ == TestOneofOneofCase.OneofMessage ? (global::IncrementalTest.Step2.AllFieldTypesV3) testOneof_ : null; }
      set {
        testOneof_ = value;
        testOneofCase_ = value == null ? TestOneofOneofCase.None : TestOneofOneofCase.OneofMessage;
      }
    }

    /// <summary>Field number for the "oneof_bytes" field.</summary>
    public const int OneofBytesFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString OneofBytes {
      get { return HasOneofBytes ? (pb::ByteString) testOneof_ : pb::ByteString.Empty; }
      set {
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.OneofBytes;
      }
    }
    /// <summary>Gets whether the "oneof_bytes" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofBytes {
      get { return testOneofCase_ == TestOneofOneofCase.OneofBytes; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_bytes" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofBytes() {
      if (HasOneofBytes) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "regular_field" field.</summary>
    public const int RegularFieldFieldNumber = 6;
    private string regularField_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RegularField {
      get { return regularField_; }
      set {
        regularField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oneof_bool" field.</summary>
    public const int OneofBoolFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OneofBool {
      get { return HasOneofBool ? (bool) secondOneof_ : false; }
      set {
        secondOneof_ = value;
        secondOneofCase_ = SecondOneofOneofCase.OneofBool;
      }
    }
    /// <summary>Gets whether the "oneof_bool" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofBool {
      get { return secondOneofCase_ == SecondOneofOneofCase.OneofBool; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_bool" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofBool() {
      if (HasOneofBool) {
        ClearSecondOneof();
      }
    }

    /// <summary>Field number for the "oneof_double" field.</summary>
    public const int OneofDoubleFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double OneofDouble {
      get { return HasOneofDouble ? (double) secondOneof_ : 0D; }
      set {
        secondOneof_ = value;
        secondOneofCase_ = SecondOneofOneofCase.OneofDouble;
      }
    }
    /// <summary>Gets whether the "oneof_double" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneofDouble {
      get { return secondOneofCase_ == SecondOneofOneofCase.OneofDouble; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneof_double" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofDouble() {
      if (HasOneofDouble) {
        ClearSecondOneof();
      }
    }

    private object testOneof_;
    /// <summary>Enum of possible cases for the "test_oneof" oneof.</summary>
    public enum TestOneofOneofCase {
      None = 0,
      OneofString = 1,
      OneofInt32 = 2,
      OneofEnum = 3,
      OneofMessage = 4,
      OneofBytes = 5,
    }
    private TestOneofOneofCase testOneofCase_ = TestOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestOneofOneofCase TestOneofCase {
      get { return testOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTestOneof() {
      testOneofCase_ = TestOneofOneofCase.None;
      testOneof_ = null;
    }

    private object secondOneof_;
    /// <summary>Enum of possible cases for the "second_oneof" oneof.</summary>
    public enum SecondOneofOneofCase {
      None = 0,
      OneofBool = 7,
      OneofDouble = 8,
    }
    private SecondOneofOneofCase secondOneofCase_ = SecondOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecondOneofOneofCase SecondOneofCase {
      get { return secondOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSecondOneof() {
      secondOneofCase_ = SecondOneofOneofCase.None;
      secondOneof_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OneofMessageV3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OneofMessageV3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OneofString != other.OneofString) return false;
      if (OneofInt32 != other.OneofInt32) return false;
      if (OneofEnum != other.OneofEnum) return false;
      if (!object.Equals(OneofMessage, other.OneofMessage)) return false;
      if (OneofBytes != other.OneofBytes) return false;
      if (RegularField != other.RegularField) return false;
      if (OneofBool != other.OneofBool) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(OneofDouble, other.OneofDouble)) return false;
      if (TestOneofCase != other.TestOneofCase) return false;
      if (SecondOneofCase != other.SecondOneofCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOneofString) hash ^= OneofString.GetHashCode();
      if (HasOneofInt32) hash ^= OneofInt32.GetHashCode();
      if (HasOneofEnum) hash ^= OneofEnum.GetHashCode();
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) hash ^= OneofMessage.GetHashCode();
      if (HasOneofBytes) hash ^= OneofBytes.GetHashCode();
      if (RegularField.Length != 0) hash ^= RegularField.GetHashCode();
      if (HasOneofBool) hash ^= OneofBool.GetHashCode();
      if (HasOneofDouble) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(OneofDouble);
      hash ^= (int) testOneofCase_;
      hash ^= (int) secondOneofCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOneofString) {
        output.WriteRawTag(10);
        output.WriteString(OneofString);
      }
      if (HasOneofInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(OneofInt32);
      }
      if (HasOneofEnum) {
        output.WriteRawTag(24);
        output.WriteEnum((int) OneofEnum);
      }
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
        output.WriteRawTag(34);
        output.WriteMessage(OneofMessage);
      }
      if (HasOneofBytes) {
        output.WriteRawTag(42);
        output.WriteBytes(OneofBytes);
      }
      if (RegularField.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RegularField);
      }
      if (HasOneofBool) {
        output.WriteRawTag(56);
        output.WriteBool(OneofBool);
      }
      if (HasOneofDouble) {
        output.WriteRawTag(65);
        output.WriteDouble(OneofDouble);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOneofString) {
        output.WriteRawTag(10);
        output.WriteString(OneofString);
      }
      if (HasOneofInt32) {
        output.WriteRawTag(16);
        output.WriteInt32(OneofInt32);
      }
      if (HasOneofEnum) {
        output.WriteRawTag(24);
        output.WriteEnum((int) OneofEnum);
      }
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
        output.WriteRawTag(34);
        output.WriteMessage(OneofMessage);
      }
      if (HasOneofBytes) {
        output.WriteRawTag(42);
        output.WriteBytes(OneofBytes);
      }
      if (RegularField.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RegularField);
      }
      if (HasOneofBool) {
        output.WriteRawTag(56);
        output.WriteBool(OneofBool);
      }
      if (HasOneofDouble) {
        output.WriteRawTag(65);
        output.WriteDouble(OneofDouble);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOneofString) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OneofString);
      }
      if (HasOneofInt32) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OneofInt32);
      }
      if (HasOneofEnum) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OneofEnum);
      }
      if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OneofMessage);
      }
      if (HasOneofBytes) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OneofBytes);
      }
      if (RegularField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RegularField);
      }
      if (HasOneofBool) {
        size += 1 + 1;
      }
      if (HasOneofDouble) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OneofMessageV3 other) {
      if (other == null) {
        return;
      }
      if (other.RegularField.Length != 0) {
        RegularField = other.RegularField;
      }
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.OneofString:
          OneofString = other.OneofString;
          break;
        case TestOneofOneofCase.OneofInt32:
          OneofInt32 = other.OneofInt32;
          break;
        case TestOneofOneofCase.OneofEnum:
          OneofEnum = other.OneofEnum;
          break;
        case TestOneofOneofCase.OneofMessage:
          if (OneofMessage == null) {
            OneofMessage = new global::IncrementalTest.Step2.AllFieldTypesV3();
          }
          OneofMessage.MergeFrom(other.OneofMessage);
          break;
        case TestOneofOneofCase.OneofBytes:
          OneofBytes = other.OneofBytes;
          break;
      }

      switch (other.SecondOneofCase) {
        case SecondOneofOneofCase.OneofBool:
          OneofBool = other.OneofBool;
          break;
        case SecondOneofOneofCase.OneofDouble:
          OneofDouble = other.OneofDouble;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OneofString = input.ReadString();
            break;
          }
          case 16: {
            OneofInt32 = input.ReadInt32();
            break;
          }
          case 24: {
            testOneof_ = input.ReadEnum();
            testOneofCase_ = TestOneofOneofCase.OneofEnum;
            break;
          }
          case 34: {
            global::IncrementalTest.Step2.AllFieldTypesV3 subBuilder = new global::IncrementalTest.Step2.AllFieldTypesV3();
            if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
              subBuilder.MergeFrom(OneofMessage);
            }
            input.ReadMessage(subBuilder);
            OneofMessage = subBuilder;
            break;
          }
          case 42: {
            OneofBytes = input.ReadBytes();
            break;
          }
          case 50: {
            RegularField = input.ReadString();
            break;
          }
          case 56: {
            OneofBool = input.ReadBool();
            break;
          }
          case 65: {
            OneofDouble = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OneofString = input.ReadString();
            break;
          }
          case 16: {
            OneofInt32 = input.ReadInt32();
            break;
          }
          case 24: {
            testOneof_ = input.ReadEnum();
            testOneofCase_ = TestOneofOneofCase.OneofEnum;
            break;
          }
          case 34: {
            global::IncrementalTest.Step2.AllFieldTypesV3 subBuilder = new global::IncrementalTest.Step2.AllFieldTypesV3();
            if (testOneofCase_ == TestOneofOneofCase.OneofMessage) {
              subBuilder.MergeFrom(OneofMessage);
            }
            input.ReadMessage(subBuilder);
            OneofMessage = subBuilder;
            break;
          }
          case 42: {
            OneofBytes = input.ReadBytes();
            break;
          }
          case 50: {
            RegularField = input.ReadString();
            break;
          }
          case 56: {
            OneofBool = input.ReadBool();
            break;
          }
          case 65: {
            OneofDouble = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
