// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: IsolatedExtension.proto
// Protobuf Java Version: 4.33.4

package Isolated;

@com.google.protobuf.Generated
public final class IsolatedExtension extends com.google.protobuf.GeneratedFile {
  private IsolatedExtension() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "IsolatedExtension");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Isolated.IsolatedExtension.extendedString);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExtendableMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Isolated.ExtendableMessage)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<ExtendableMessage> {

    /**
     * <code>optional string base_field = 1;</code>
     * @return Whether the baseField field is set.
     */
    boolean hasBaseField();
    /**
     * <code>optional string base_field = 1;</code>
     * @return The baseField.
     */
    java.lang.String getBaseField();
    /**
     * <code>optional string base_field = 1;</code>
     * @return The bytes for baseField.
     */
    com.google.protobuf.ByteString
        getBaseFieldBytes();
  }
  /**
   * Protobuf type {@code Isolated.ExtendableMessage}
   */
  public static final class ExtendableMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ExtendableMessage> implements
      // @@protoc_insertion_point(message_implements:Isolated.ExtendableMessage)
      ExtendableMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 4,
        /* suffix= */ "",
        "ExtendableMessage");
    }
    // Use ExtendableMessage.newBuilder() to construct.
    private ExtendableMessage(com.google.protobuf.GeneratedMessage.ExtendableBuilder<Isolated.IsolatedExtension.ExtendableMessage, ?> builder) {
      super(builder);
    }
    private ExtendableMessage() {
      baseField_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Isolated.IsolatedExtension.internal_static_Isolated_ExtendableMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Isolated.IsolatedExtension.internal_static_Isolated_ExtendableMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Isolated.IsolatedExtension.ExtendableMessage.class, Isolated.IsolatedExtension.ExtendableMessage.Builder.class);
    }

    private int bitField0_;
    public static final int BASE_FIELD_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object baseField_ = "";
    /**
     * <code>optional string base_field = 1;</code>
     * @return Whether the baseField field is set.
     */
    @java.lang.Override
    public boolean hasBaseField() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string base_field = 1;</code>
     * @return The baseField.
     */
    @java.lang.Override
    public java.lang.String getBaseField() {
      java.lang.Object ref = baseField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          baseField_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string base_field = 1;</code>
     * @return The bytes for baseField.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBaseFieldBytes() {
      java.lang.Object ref = baseField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage.ExtensionSerializer
          extensionWriter = newExtensionSerializer();
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, baseField_);
      }
      extensionWriter.writeUntil(200, output);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, baseField_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Isolated.IsolatedExtension.ExtendableMessage)) {
        return super.equals(obj);
      }
      Isolated.IsolatedExtension.ExtendableMessage other = (Isolated.IsolatedExtension.ExtendableMessage) obj;

      if (hasBaseField() != other.hasBaseField()) return false;
      if (hasBaseField()) {
        if (!getBaseField()
            .equals(other.getBaseField())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      if (!getExtensionFields().equals(other.getExtensionFields()))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseField()) {
        hash = (37 * hash) + BASE_FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getBaseField().hashCode();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Isolated.IsolatedExtension.ExtendableMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Isolated.IsolatedExtension.ExtendableMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Isolated.IsolatedExtension.ExtendableMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Isolated.IsolatedExtension.ExtendableMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Isolated.ExtendableMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          Isolated.IsolatedExtension.ExtendableMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:Isolated.ExtendableMessage)
        Isolated.IsolatedExtension.ExtendableMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Isolated.IsolatedExtension.internal_static_Isolated_ExtendableMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Isolated.IsolatedExtension.internal_static_Isolated_ExtendableMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Isolated.IsolatedExtension.ExtendableMessage.class, Isolated.IsolatedExtension.ExtendableMessage.Builder.class);
      }

      // Construct using Isolated.IsolatedExtension.ExtendableMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        baseField_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Isolated.IsolatedExtension.internal_static_Isolated_ExtendableMessage_descriptor;
      }

      @java.lang.Override
      public Isolated.IsolatedExtension.ExtendableMessage getDefaultInstanceForType() {
        return Isolated.IsolatedExtension.ExtendableMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Isolated.IsolatedExtension.ExtendableMessage build() {
        Isolated.IsolatedExtension.ExtendableMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Isolated.IsolatedExtension.ExtendableMessage buildPartial() {
        Isolated.IsolatedExtension.ExtendableMessage result = new Isolated.IsolatedExtension.ExtendableMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Isolated.IsolatedExtension.ExtendableMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.baseField_ = baseField_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Isolated.IsolatedExtension.ExtendableMessage, Type> extension,
          Type value) {
        return super.setExtension(extension, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Isolated.IsolatedExtension.ExtendableMessage, java.util.List<Type>> extension,
          int index, Type value) {
        return super.setExtension(extension, index, value);
      }
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Isolated.IsolatedExtension.ExtendableMessage, java.util.List<Type>> extension,
          Type value) {
        return super.addExtension(extension, value);
      }
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Isolated.IsolatedExtension.ExtendableMessage, Type> extension) {
        return super.clearExtension(extension);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Isolated.IsolatedExtension.ExtendableMessage) {
          return mergeFrom((Isolated.IsolatedExtension.ExtendableMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Isolated.IsolatedExtension.ExtendableMessage other) {
        if (other == Isolated.IsolatedExtension.ExtendableMessage.getDefaultInstance()) return this;
        if (other.hasBaseField()) {
          baseField_ = other.baseField_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                baseField_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object baseField_ = "";
      /**
       * <code>optional string base_field = 1;</code>
       * @return Whether the baseField field is set.
       */
      public boolean hasBaseField() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string base_field = 1;</code>
       * @return The baseField.
       */
      public java.lang.String getBaseField() {
        java.lang.Object ref = baseField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            baseField_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string base_field = 1;</code>
       * @return The bytes for baseField.
       */
      public com.google.protobuf.ByteString
          getBaseFieldBytes() {
        java.lang.Object ref = baseField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string base_field = 1;</code>
       * @param value The baseField to set.
       * @return This builder for chaining.
       */
      public Builder setBaseField(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        baseField_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string base_field = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseField() {
        baseField_ = getDefaultInstance().getBaseField();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string base_field = 1;</code>
       * @param value The bytes for baseField to set.
       * @return This builder for chaining.
       */
      public Builder setBaseFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        baseField_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Isolated.ExtendableMessage)
    }

    // @@protoc_insertion_point(class_scope:Isolated.ExtendableMessage)
    private static final Isolated.IsolatedExtension.ExtendableMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Isolated.IsolatedExtension.ExtendableMessage();
    }

    public static Isolated.IsolatedExtension.ExtendableMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExtendableMessage>
        PARSER = new com.google.protobuf.AbstractParser<ExtendableMessage>() {
      @java.lang.Override
      public ExtendableMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExtendableMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExtendableMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Isolated.IsolatedExtension.ExtendableMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int EXTENDED_STRING_FIELD_NUMBER = 100;
  /**
   * <code>extend .Isolated.ExtendableMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      Isolated.IsolatedExtension.ExtendableMessage,
      java.lang.String> extendedString = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Isolated_ExtendableMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Isolated_ExtendableMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027IsolatedExtension.proto\022\010Isolated\".\n\021E" +
      "xtendableMessage\022\022\n\nbase_field\030\001 \001(\t*\005\010d" +
      "\020\310\001:4\n\017extended_string\022\033.Isolated.Extend" +
      "ableMessage\030d \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Isolated_ExtendableMessage_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Isolated_ExtendableMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Isolated_ExtendableMessage_descriptor,
        new java.lang.String[] { "BaseField", });
    extendedString.internalInit(descriptor.getExtension(0));
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
