// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: IsolatedGroup.proto
// Protobuf Java Version: 4.33.4

package Isolated;

@com.google.protobuf.Generated
public final class IsolatedGroup extends com.google.protobuf.GeneratedFile {
  private IsolatedGroup() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "IsolatedGroup");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Isolated.GroupMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional group TestGroup = 1 { ... }</code>
     * @return Whether the testgroup field is set.
     */
    boolean hasTestGroup();
    /**
     * <code>optional group TestGroup = 1 { ... }</code>
     * @return The testgroup.
     */
    Isolated.IsolatedGroup.GroupMessage.TestGroup getTestGroup();
    /**
     * <code>optional group TestGroup = 1 { ... }</code>
     */
    Isolated.IsolatedGroup.GroupMessage.TestGroupOrBuilder getTestGroupOrBuilder();
  }
  /**
   * Protobuf type {@code Isolated.GroupMessage}
   */
  public static final class GroupMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Isolated.GroupMessage)
      GroupMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 4,
        /* suffix= */ "",
        "GroupMessage");
    }
    // Use GroupMessage.newBuilder() to construct.
    private GroupMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GroupMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Isolated.IsolatedGroup.GroupMessage.class, Isolated.IsolatedGroup.GroupMessage.Builder.class);
    }

    public interface TestGroupOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Isolated.GroupMessage.TestGroup)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string group_field = 1;</code>
       * @return Whether the groupField field is set.
       */
      boolean hasGroupField();
      /**
       * <code>optional string group_field = 1;</code>
       * @return The groupField.
       */
      java.lang.String getGroupField();
      /**
       * <code>optional string group_field = 1;</code>
       * @return The bytes for groupField.
       */
      com.google.protobuf.ByteString
          getGroupFieldBytes();
    }
    /**
     * Protobuf type {@code Isolated.GroupMessage.TestGroup}
     */
    public static final class TestGroup extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Isolated.GroupMessage.TestGroup)
        TestGroupOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 33,
          /* patch= */ 4,
          /* suffix= */ "",
          "TestGroup");
      }
      // Use TestGroup.newBuilder() to construct.
      private TestGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private TestGroup() {
        groupField_ = "";
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_TestGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_TestGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Isolated.IsolatedGroup.GroupMessage.TestGroup.class, Isolated.IsolatedGroup.GroupMessage.TestGroup.Builder.class);
      }

      private int bitField0_;
      public static final int GROUP_FIELD_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object groupField_ = "";
      /**
       * <code>optional string group_field = 1;</code>
       * @return Whether the groupField field is set.
       */
      @java.lang.Override
      public boolean hasGroupField() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string group_field = 1;</code>
       * @return The groupField.
       */
      @java.lang.Override
      public java.lang.String getGroupField() {
        java.lang.Object ref = groupField_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            groupField_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string group_field = 1;</code>
       * @return The bytes for groupField.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getGroupFieldBytes() {
        java.lang.Object ref = groupField_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 1, groupField_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(1, groupField_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Isolated.IsolatedGroup.GroupMessage.TestGroup)) {
          return super.equals(obj);
        }
        Isolated.IsolatedGroup.GroupMessage.TestGroup other = (Isolated.IsolatedGroup.GroupMessage.TestGroup) obj;

        if (hasGroupField() != other.hasGroupField()) return false;
        if (hasGroupField()) {
          if (!getGroupField()
              .equals(other.getGroupField())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasGroupField()) {
          hash = (37 * hash) + GROUP_FIELD_FIELD_NUMBER;
          hash = (53 * hash) + getGroupField().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static Isolated.IsolatedGroup.GroupMessage.TestGroup parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Isolated.IsolatedGroup.GroupMessage.TestGroup prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Isolated.GroupMessage.TestGroup}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Isolated.GroupMessage.TestGroup)
          Isolated.IsolatedGroup.GroupMessage.TestGroupOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_TestGroup_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_TestGroup_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Isolated.IsolatedGroup.GroupMessage.TestGroup.class, Isolated.IsolatedGroup.GroupMessage.TestGroup.Builder.class);
        }

        // Construct using Isolated.IsolatedGroup.GroupMessage.TestGroup.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          groupField_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_TestGroup_descriptor;
        }

        @java.lang.Override
        public Isolated.IsolatedGroup.GroupMessage.TestGroup getDefaultInstanceForType() {
          return Isolated.IsolatedGroup.GroupMessage.TestGroup.getDefaultInstance();
        }

        @java.lang.Override
        public Isolated.IsolatedGroup.GroupMessage.TestGroup build() {
          Isolated.IsolatedGroup.GroupMessage.TestGroup result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public Isolated.IsolatedGroup.GroupMessage.TestGroup buildPartial() {
          Isolated.IsolatedGroup.GroupMessage.TestGroup result = new Isolated.IsolatedGroup.GroupMessage.TestGroup(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(Isolated.IsolatedGroup.GroupMessage.TestGroup result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.groupField_ = groupField_;
            to_bitField0_ |= 0x00000001;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Isolated.IsolatedGroup.GroupMessage.TestGroup) {
            return mergeFrom((Isolated.IsolatedGroup.GroupMessage.TestGroup)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Isolated.IsolatedGroup.GroupMessage.TestGroup other) {
          if (other == Isolated.IsolatedGroup.GroupMessage.TestGroup.getDefaultInstance()) return this;
          if (other.hasGroupField()) {
            groupField_ = other.groupField_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  groupField_ = input.readBytes();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object groupField_ = "";
        /**
         * <code>optional string group_field = 1;</code>
         * @return Whether the groupField field is set.
         */
        public boolean hasGroupField() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string group_field = 1;</code>
         * @return The groupField.
         */
        public java.lang.String getGroupField() {
          java.lang.Object ref = groupField_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              groupField_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string group_field = 1;</code>
         * @return The bytes for groupField.
         */
        public com.google.protobuf.ByteString
            getGroupFieldBytes() {
          java.lang.Object ref = groupField_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            groupField_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string group_field = 1;</code>
         * @param value The groupField to set.
         * @return This builder for chaining.
         */
        public Builder setGroupField(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          groupField_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>optional string group_field = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearGroupField() {
          groupField_ = getDefaultInstance().getGroupField();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>optional string group_field = 1;</code>
         * @param value The bytes for groupField to set.
         * @return This builder for chaining.
         */
        public Builder setGroupFieldBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          groupField_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Isolated.GroupMessage.TestGroup)
      }

      // @@protoc_insertion_point(class_scope:Isolated.GroupMessage.TestGroup)
      private static final Isolated.IsolatedGroup.GroupMessage.TestGroup DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Isolated.IsolatedGroup.GroupMessage.TestGroup();
      }

      public static Isolated.IsolatedGroup.GroupMessage.TestGroup getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<TestGroup>
          PARSER = new com.google.protobuf.AbstractParser<TestGroup>() {
        @java.lang.Override
        public TestGroup parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<TestGroup> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<TestGroup> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public Isolated.IsolatedGroup.GroupMessage.TestGroup getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TESTGROUP_FIELD_NUMBER = 1;
    private Isolated.IsolatedGroup.GroupMessage.TestGroup testGroup_;
    /**
     * <code>optional group TestGroup = 1 { ... }</code>
     * @return Whether the testgroup field is set.
     */
    @java.lang.Override
    public boolean hasTestGroup() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional group TestGroup = 1 { ... }</code>
     * @return The testgroup.
     */
    @java.lang.Override
    public Isolated.IsolatedGroup.GroupMessage.TestGroup getTestGroup() {
      return testGroup_ == null ? Isolated.IsolatedGroup.GroupMessage.TestGroup.getDefaultInstance() : testGroup_;
    }
    /**
     * <code>optional group TestGroup = 1 { ... }</code>
     */
    @java.lang.Override
    public Isolated.IsolatedGroup.GroupMessage.TestGroupOrBuilder getTestGroupOrBuilder() {
      return testGroup_ == null ? Isolated.IsolatedGroup.GroupMessage.TestGroup.getDefaultInstance() : testGroup_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeGroup(1, getTestGroup());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeGroupSize(1, getTestGroup());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Isolated.IsolatedGroup.GroupMessage)) {
        return super.equals(obj);
      }
      Isolated.IsolatedGroup.GroupMessage other = (Isolated.IsolatedGroup.GroupMessage) obj;

      if (hasTestGroup() != other.hasTestGroup()) return false;
      if (hasTestGroup()) {
        if (!getTestGroup()
            .equals(other.getTestGroup())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestGroup()) {
        hash = (37 * hash) + TESTGROUP_FIELD_NUMBER;
        hash = (53 * hash) + getTestGroup().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Isolated.IsolatedGroup.GroupMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Isolated.IsolatedGroup.GroupMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Isolated.IsolatedGroup.GroupMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Isolated.IsolatedGroup.GroupMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Isolated.GroupMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Isolated.GroupMessage)
        Isolated.IsolatedGroup.GroupMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Isolated.IsolatedGroup.GroupMessage.class, Isolated.IsolatedGroup.GroupMessage.Builder.class);
      }

      // Construct using Isolated.IsolatedGroup.GroupMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetTestGroupFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        testGroup_ = null;
        if (testGroupBuilder_ != null) {
          testGroupBuilder_.dispose();
          testGroupBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Isolated.IsolatedGroup.internal_static_Isolated_GroupMessage_descriptor;
      }

      @java.lang.Override
      public Isolated.IsolatedGroup.GroupMessage getDefaultInstanceForType() {
        return Isolated.IsolatedGroup.GroupMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Isolated.IsolatedGroup.GroupMessage build() {
        Isolated.IsolatedGroup.GroupMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Isolated.IsolatedGroup.GroupMessage buildPartial() {
        Isolated.IsolatedGroup.GroupMessage result = new Isolated.IsolatedGroup.GroupMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Isolated.IsolatedGroup.GroupMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.testGroup_ = testGroupBuilder_ == null
              ? testGroup_
              : testGroupBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Isolated.IsolatedGroup.GroupMessage) {
          return mergeFrom((Isolated.IsolatedGroup.GroupMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Isolated.IsolatedGroup.GroupMessage other) {
        if (other == Isolated.IsolatedGroup.GroupMessage.getDefaultInstance()) return this;
        if (other.hasTestGroup()) {
          mergeTestGroup(other.getTestGroup());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 11: {
                input.readGroup(1,
                    internalGetTestGroupFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 11
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Isolated.IsolatedGroup.GroupMessage.TestGroup testGroup_;
      private com.google.protobuf.SingleFieldBuilder<
          Isolated.IsolatedGroup.GroupMessage.TestGroup, Isolated.IsolatedGroup.GroupMessage.TestGroup.Builder, Isolated.IsolatedGroup.GroupMessage.TestGroupOrBuilder> testGroupBuilder_;
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       * @return Whether the testgroup field is set.
       */
      public boolean hasTestGroup() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       * @return The testgroup.
       */
      public Isolated.IsolatedGroup.GroupMessage.TestGroup getTestGroup() {
        if (testGroupBuilder_ == null) {
          return testGroup_ == null ? Isolated.IsolatedGroup.GroupMessage.TestGroup.getDefaultInstance() : testGroup_;
        } else {
          return testGroupBuilder_.getMessage();
        }
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       */
      public Builder setTestGroup(Isolated.IsolatedGroup.GroupMessage.TestGroup value) {
        if (testGroupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          testGroup_ = value;
        } else {
          testGroupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       */
      public Builder setTestGroup(
          Isolated.IsolatedGroup.GroupMessage.TestGroup.Builder builderForValue) {
        if (testGroupBuilder_ == null) {
          testGroup_ = builderForValue.build();
        } else {
          testGroupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       */
      public Builder mergeTestGroup(Isolated.IsolatedGroup.GroupMessage.TestGroup value) {
        if (testGroupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            testGroup_ != null &&
            testGroup_ != Isolated.IsolatedGroup.GroupMessage.TestGroup.getDefaultInstance()) {
            getTestGroupBuilder().mergeFrom(value);
          } else {
            testGroup_ = value;
          }
        } else {
          testGroupBuilder_.mergeFrom(value);
        }
        if (testGroup_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       */
      public Builder clearTestGroup() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testGroup_ = null;
        if (testGroupBuilder_ != null) {
          testGroupBuilder_.dispose();
          testGroupBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       */
      public Isolated.IsolatedGroup.GroupMessage.TestGroup.Builder getTestGroupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetTestGroupFieldBuilder().getBuilder();
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       */
      public Isolated.IsolatedGroup.GroupMessage.TestGroupOrBuilder getTestGroupOrBuilder() {
        if (testGroupBuilder_ != null) {
          return testGroupBuilder_.getMessageOrBuilder();
        } else {
          return testGroup_ == null ?
              Isolated.IsolatedGroup.GroupMessage.TestGroup.getDefaultInstance() : testGroup_;
        }
      }
      /**
       * <code>optional group TestGroup = 1 { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Isolated.IsolatedGroup.GroupMessage.TestGroup, Isolated.IsolatedGroup.GroupMessage.TestGroup.Builder, Isolated.IsolatedGroup.GroupMessage.TestGroupOrBuilder>
          internalGetTestGroupFieldBuilder() {
        if (testGroupBuilder_ == null) {
          testGroupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Isolated.IsolatedGroup.GroupMessage.TestGroup, Isolated.IsolatedGroup.GroupMessage.TestGroup.Builder, Isolated.IsolatedGroup.GroupMessage.TestGroupOrBuilder>(
                  getTestGroup(),
                  getParentForChildren(),
                  isClean());
          testGroup_ = null;
        }
        return testGroupBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Isolated.GroupMessage)
    }

    // @@protoc_insertion_point(class_scope:Isolated.GroupMessage)
    private static final Isolated.IsolatedGroup.GroupMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Isolated.IsolatedGroup.GroupMessage();
    }

    public static Isolated.IsolatedGroup.GroupMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupMessage>
        PARSER = new com.google.protobuf.AbstractParser<GroupMessage>() {
      @java.lang.Override
      public GroupMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GroupMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Isolated.IsolatedGroup.GroupMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Isolated_GroupMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Isolated_GroupMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Isolated_GroupMessage_TestGroup_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Isolated_GroupMessage_TestGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023IsolatedGroup.proto\022\010Isolated\"e\n\014Group" +
      "Message\0223\n\ttestgroup\030\001 \001(\n2 .Isolated.Gr" +
      "oupMessage.TestGroup\032 \n\tTestGroup\022\023\n\013gro" +
      "up_field\030\001 \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Isolated_GroupMessage_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Isolated_GroupMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Isolated_GroupMessage_descriptor,
        new java.lang.String[] { "TestGroup", });
    internal_static_Isolated_GroupMessage_TestGroup_descriptor =
      internal_static_Isolated_GroupMessage_descriptor.getNestedType(0);
    internal_static_Isolated_GroupMessage_TestGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Isolated_GroupMessage_TestGroup_descriptor,
        new java.lang.String[] { "GroupField", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
