// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: IsolatedReserved.proto
// Protobuf Java Version: 4.33.4

package Isolated;

@com.google.protobuf.Generated
public final class IsolatedReserved extends com.google.protobuf.GeneratedFile {
  private IsolatedReserved() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "IsolatedReserved");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReservedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Isolated.ReservedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    boolean hasField1();
    /**
     * <code>optional string field1 = 1;</code>
     * @return The field1.
     */
    java.lang.String getField1();
    /**
     * <code>optional string field1 = 1;</code>
     * @return The bytes for field1.
     */
    com.google.protobuf.ByteString
        getField1Bytes();

    /**
     * <code>optional int32 field3 = 3;</code>
     * @return Whether the field3 field is set.
     */
    boolean hasField3();
    /**
     * <code>optional int32 field3 = 3;</code>
     * @return The field3.
     */
    int getField3();
  }
  /**
   * Protobuf type {@code Isolated.ReservedMessage}
   */
  public static final class ReservedMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Isolated.ReservedMessage)
      ReservedMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 4,
        /* suffix= */ "",
        "ReservedMessage");
    }
    // Use ReservedMessage.newBuilder() to construct.
    private ReservedMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReservedMessage() {
      field1_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Isolated.IsolatedReserved.internal_static_Isolated_ReservedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Isolated.IsolatedReserved.internal_static_Isolated_ReservedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Isolated.IsolatedReserved.ReservedMessage.class, Isolated.IsolatedReserved.ReservedMessage.Builder.class);
    }

    private int bitField0_;
    public static final int FIELD1_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object field1_ = "";
    /**
     * <code>optional string field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    @java.lang.Override
    public boolean hasField1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string field1 = 1;</code>
     * @return The field1.
     */
    @java.lang.Override
    public java.lang.String getField1() {
      java.lang.Object ref = field1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          field1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string field1 = 1;</code>
     * @return The bytes for field1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getField1Bytes() {
      java.lang.Object ref = field1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD3_FIELD_NUMBER = 3;
    private int field3_ = 0;
    /**
     * <code>optional int32 field3 = 3;</code>
     * @return Whether the field3 field is set.
     */
    @java.lang.Override
    public boolean hasField3() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 field3 = 3;</code>
     * @return The field3.
     */
    @java.lang.Override
    public int getField3() {
      return field3_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, field1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, field3_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, field1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, field3_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Isolated.IsolatedReserved.ReservedMessage)) {
        return super.equals(obj);
      }
      Isolated.IsolatedReserved.ReservedMessage other = (Isolated.IsolatedReserved.ReservedMessage) obj;

      if (hasField1() != other.hasField1()) return false;
      if (hasField1()) {
        if (!getField1()
            .equals(other.getField1())) return false;
      }
      if (hasField3() != other.hasField3()) return false;
      if (hasField3()) {
        if (getField3()
            != other.getField3()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField1()) {
        hash = (37 * hash) + FIELD1_FIELD_NUMBER;
        hash = (53 * hash) + getField1().hashCode();
      }
      if (hasField3()) {
        hash = (37 * hash) + FIELD3_FIELD_NUMBER;
        hash = (53 * hash) + getField3();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Isolated.IsolatedReserved.ReservedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Isolated.IsolatedReserved.ReservedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Isolated.IsolatedReserved.ReservedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Isolated.IsolatedReserved.ReservedMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Isolated.ReservedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Isolated.ReservedMessage)
        Isolated.IsolatedReserved.ReservedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Isolated.IsolatedReserved.internal_static_Isolated_ReservedMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Isolated.IsolatedReserved.internal_static_Isolated_ReservedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Isolated.IsolatedReserved.ReservedMessage.class, Isolated.IsolatedReserved.ReservedMessage.Builder.class);
      }

      // Construct using Isolated.IsolatedReserved.ReservedMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        field1_ = "";
        field3_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Isolated.IsolatedReserved.internal_static_Isolated_ReservedMessage_descriptor;
      }

      @java.lang.Override
      public Isolated.IsolatedReserved.ReservedMessage getDefaultInstanceForType() {
        return Isolated.IsolatedReserved.ReservedMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Isolated.IsolatedReserved.ReservedMessage build() {
        Isolated.IsolatedReserved.ReservedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Isolated.IsolatedReserved.ReservedMessage buildPartial() {
        Isolated.IsolatedReserved.ReservedMessage result = new Isolated.IsolatedReserved.ReservedMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Isolated.IsolatedReserved.ReservedMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.field1_ = field1_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.field3_ = field3_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Isolated.IsolatedReserved.ReservedMessage) {
          return mergeFrom((Isolated.IsolatedReserved.ReservedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Isolated.IsolatedReserved.ReservedMessage other) {
        if (other == Isolated.IsolatedReserved.ReservedMessage.getDefaultInstance()) return this;
        if (other.hasField1()) {
          field1_ = other.field1_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasField3()) {
          setField3(other.getField3());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                field1_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 24: {
                field3_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object field1_ = "";
      /**
       * <code>optional string field1 = 1;</code>
       * @return Whether the field1 field is set.
       */
      public boolean hasField1() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string field1 = 1;</code>
       * @return The field1.
       */
      public java.lang.String getField1() {
        java.lang.Object ref = field1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            field1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string field1 = 1;</code>
       * @return The bytes for field1.
       */
      public com.google.protobuf.ByteString
          getField1Bytes() {
        java.lang.Object ref = field1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string field1 = 1;</code>
       * @param value The field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        field1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string field1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField1() {
        field1_ = getDefaultInstance().getField1();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string field1 = 1;</code>
       * @param value The bytes for field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        field1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int field3_ ;
      /**
       * <code>optional int32 field3 = 3;</code>
       * @return Whether the field3 field is set.
       */
      @java.lang.Override
      public boolean hasField3() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 field3 = 3;</code>
       * @return The field3.
       */
      @java.lang.Override
      public int getField3() {
        return field3_;
      }
      /**
       * <code>optional int32 field3 = 3;</code>
       * @param value The field3 to set.
       * @return This builder for chaining.
       */
      public Builder setField3(int value) {

        field3_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 field3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearField3() {
        bitField0_ = (bitField0_ & ~0x00000002);
        field3_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Isolated.ReservedMessage)
    }

    // @@protoc_insertion_point(class_scope:Isolated.ReservedMessage)
    private static final Isolated.IsolatedReserved.ReservedMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Isolated.IsolatedReserved.ReservedMessage();
    }

    public static Isolated.IsolatedReserved.ReservedMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReservedMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReservedMessage>() {
      @java.lang.Override
      public ReservedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReservedMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReservedMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Isolated.IsolatedReserved.ReservedMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Isolated_ReservedMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Isolated_ReservedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026IsolatedReserved.proto\022\010Isolated\"M\n\017Re" +
      "servedMessage\022\016\n\006field1\030\001 \001(\t\022\016\n\006field3\030" +
      "\003 \001(\005J\004\010\002\020\003J\004\010\017\020\020J\004\010\t\020\014R\003fooR\003bar"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Isolated_ReservedMessage_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Isolated_ReservedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Isolated_ReservedMessage_descriptor,
        new java.lang.String[] { "Field1", "Field3", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
