package com.rubberjam.protobuf.compiler.java;

import com.google.protobuf.DescriptorProtos.FileOptions;
import com.google.protobuf.Descriptors.Descriptor;
import com.google.protobuf.Descriptors.EnumDescriptor;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.Descriptors.FileDescriptor;
import com.google.protobuf.Descriptors.ServiceDescriptor;
import com.rubberjam.protobuf.compiler.java.full.ImmutableGeneratorFactory;
import com.rubberjam.protobuf.compiler.java.lite.ImmutableLiteGeneratorFactory;
import com.rubberjam.protobuf.io.Printer;
import java.util.List;

/**
 * Generates the outer class and its contents. Ported from java/file.h and
 * java/file.cc.
 */
public class FileGenerator {

	private final FileDescriptor file;
	private final Options options;
	private final Context context;
	private final ClassNameResolver nameResolver;
	private final GeneratorFactory factory;

	public FileGenerator(FileDescriptor file, Options options) {
		// Initialize context
		Context javaContext = new Context(file, options);
		ClassNameResolver nameResolver = javaContext.getNameResolver();

		// We only support immutable code generation for now as per the conversion order
		// (Phase 8-9).
		// Select the factory based on whether Lite runtime is required.
		GeneratorFactory factory;
		if (javaContext.enforceLite()) {
			factory = new ImmutableLiteGeneratorFactory(javaContext);
		} else {
			factory = new ImmutableGeneratorFactory(javaContext);
		}
		this.file = file;
		this.options = options;
		this.context = javaContext;
		this.nameResolver = context.getNameResolver();
		this.factory = factory;
	}

	public FileGenerator(FileDescriptor file, Options options, Context context, GeneratorFactory factory) {
		this.file = file;
		this.options = options;
		this.context = context;
		this.nameResolver = context.getNameResolver();
		this.factory = factory;

	}

	/** Java package for the generated file (for output path). */
	public String getJavaPackage() {
		return nameResolver.getFileJavaPackage(file);
	}

	/** Outer class name for the generated file (for output path). */
	public String getClassName() {
		return nameResolver.getFileClassName(file, !context.enforceLite());
	}

	public boolean validate(List<String> errors) {
		// Check for package name conflicts or invalid names if necessary.
		// Basic validation.
		return true;
	}

	public void generate(Printer printer) {
		String javaPackage = file.getOptions().getJavaPackage();
		if (javaPackage.isEmpty()) {
			javaPackage = "com.google.protobuf"; // Default fallback? Or use proto package?
			if (!file.getPackage().isEmpty()) {
				javaPackage = file.getPackage();
			}
		}

		if (!javaPackage.isEmpty()) {
			printer.print("// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
					+ "// NO CHECKED-IN PROTOBUF GENCODE\n" + "// source: " + file.getName() + "\n"
					+ "// Protobuf Java Version: "
					+ com.rubberjam.protobuf.compiler.Versions.PROTOBUF_JAVA_VERSION_STRING + "\n" + "\n" + "package "
					+ javaPackage + ";\n" + "\n");
		}

		// Generate imports?
		// Java doesn't strictly require imports if we use fully qualified names.
		// And ClassNameResolver usually returns FQNs.
		// So we might not need explicit imports except for basic types.

		String classname = nameResolver.getFileClassName(file, !context.enforceLite());
		printer.print("@com.google.protobuf.Generated\n" + "public final class " + classname
				+ " extends com.google.protobuf.GeneratedFile {\n");
		printer.indent();

		printer.print("private " + classname + "() {}\n");

		com.google.protobuf.compiler.PluginProtos.Version version = com.rubberjam.protobuf.compiler.Versions
				.getProtobufJavaVersion(false);

		printer.print("static {\n" + "  com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(\n"
				+ "    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,\n" + "    /* major= */ "
				+ version.getMajor() + ",\n" + "    /* minor= */ " + version.getMinor() + ",\n" + "    /* patch= */ "
				+ version.getPatch() + ",\n" + "    /* suffix= */ \"" + version.getSuffix() + "\",\n" + "    \""
				+ classname + "\");\n" + "}\n");

		generateExtensionRegistrationCode(printer);

		boolean multipleFiles = file.getOptions().getJavaMultipleFiles();

		if (!multipleFiles) {
			for (EnumDescriptor enumType : file.getEnumTypes()) {
				factory.newEnumGenerator(enumType).generate(printer);
			}
			for (Descriptor message : file.getMessageTypes()) {
				factory.newMessageGenerator(message).generateInterface(printer);
				factory.newMessageGenerator(message).generate(printer);
			}
			if (file.getOptions().getJavaGenericServices()) {
				for (ServiceDescriptor service : file.getServices()) {
					GeneratorFactory.ServiceGenerator serviceGen = factory.newServiceGenerator(service);
					if (serviceGen != null) {
						serviceGen.generate(printer);
					}
				}
			}
		}

		for (FieldDescriptor extension : file.getExtensions()) {
			factory.newExtensionGenerator(extension).generate(printer);
		}

		int[] bytecodeEstimate = new int[] { 0 };
		for (Descriptor message : file.getMessageTypes()) {
			factory.newMessageGenerator(message).generateStaticVariables(printer, bytecodeEstimate);
		}

		printer.print("\n");
		generateDescriptorInitializationCodeForImmutable(printer);
		printer.print("\n");
		printer.print("// @@protoc_insertion_point(outer_class_scope)\n");
		printer.outdent();
		printer.print("}");
	}

	private void generateDescriptorInitializationCodeForImmutable(Printer printer) {
		printer.print("public static com.google.protobuf.Descriptors.FileDescriptor\n" + "    getDescriptor() {\n"
				+ "  return descriptor;\n" + "}\n" + "private static  com.google.protobuf.Descriptors.FileDescriptor\n"
				+ "    descriptor;\n" + "static {\n");
		printer.indent();

		new SharedCodeGenerator(file, options).generateDescriptors(printer);

		for (Descriptor message : file.getMessageTypes()) {
			factory.newMessageGenerator(message).generateStaticVariableInitializers(printer);
		}
		for (FieldDescriptor extension : file.getExtensions()) {
			factory.newExtensionGenerator(extension).generateNonNestedInitializationCode(printer);
		}

		printer.print("descriptor.resolveAllFeaturesImmutable();\n");

		for (FileDescriptor dependency : file.getDependencies()) {
			String dependencyClass = nameResolver.getImmutableClassName(dependency);
			printer.print(dependencyClass + ".getDescriptor();\n");
		}

		// Extension registry update only needed for files with extensions that have
		// custom options
		// requiring descriptor database resolution. Simple extensions don't need it.

		printer.outdent();
		printer.print("}\n");
	}

	private void generateExtensionRegistrationCode(Printer printer) {
		printer.print("public static void registerAllExtensions(\n"
				+ "    com.google.protobuf.ExtensionRegistryLite registry) {\n");
		printer.indent();
		for (FieldDescriptor extension : file.getExtensions()) {
			factory.newExtensionGenerator(extension).generateRegistrationCode(printer);
		}
		for (Descriptor message : file.getMessageTypes()) {
			factory.newMessageGenerator(message).generateExtensionRegistrationCode(printer);
		}
		printer.outdent();
		printer.print("}\n" + "\n" + "public static void registerAllExtensions(\n"
				+ "    com.google.protobuf.ExtensionRegistry registry) {\n" + "  registerAllExtensions(\n"
				+ "      (com.google.protobuf.ExtensionRegistryLite) registry);\n" + "}\n");
	}

}
