package com.rubberjam.protobuf.compiler.java;

import com.google.protobuf.Descriptors.FileDescriptor;
import com.rubberjam.protobuf.compiler.GeneratorContext;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

public class FileGenerator
{
	private final FileDescriptor file;
	private final com.google.protobuf.DescriptorProtos.FileDescriptorProto sourceProto;
	private final JavaCompilerOptions options;
	private final boolean immutableApi;
	private final JavaContext context;
	private final ClassNameResolver nameResolver;
	private final GeneratorFactory generatorFactory;
	private final String className;
	private final String javaPackage;

	private final List<MessageGenerator> messageGenerators = new ArrayList<>();
	private final List<ExtensionGenerator> extensionGenerators = new ArrayList<>();
	private final List<EnumGenerator> enumGenerators = new ArrayList<>();
	private final List<ServiceGenerator> serviceGenerators = new ArrayList<>();

	public FileGenerator(FileDescriptor file, com.google.protobuf.DescriptorProtos.FileDescriptorProto sourceProto, JavaCompilerOptions options, boolean immutableApi)
	{
		this.file = file;
		this.sourceProto = sourceProto;
		this.options = options;
		this.immutableApi = immutableApi;
		this.context = new JavaContext(file, sourceProto, options);
		this.nameResolver = context.getNameResolver();
		this.className = nameResolver.getFileClassName(file, immutableApi);
		this.javaPackage = nameResolver.getFileJavaPackage(file);

		// TODO: Choose factory based on lite/full
		if (context.enforceLite() || file.getOptions()
				.getOptimizeFor() == com.google.protobuf.DescriptorProtos.FileOptions.OptimizeMode.LITE_RUNTIME)
		{
			this.generatorFactory = new com.rubberjam.protobuf.compiler.java.lite.GeneratorFactory(context);
		}
		else
		{
			this.generatorFactory = new com.rubberjam.protobuf.compiler.java.full.GeneratorFactory(context);
		}

		for (com.google.protobuf.Descriptors.Descriptor messageType : file.getMessageTypes())
		{
			messageGenerators.add(generatorFactory.newMessageGenerator(messageType));
		}
		for (com.google.protobuf.Descriptors.FieldDescriptor extension : file.getExtensions())
		{
			extensionGenerators.add(generatorFactory.newExtensionGenerator(extension));
		}
		for (com.google.protobuf.Descriptors.EnumDescriptor enumType : file.getEnumTypes())
		{
			enumGenerators.add(generatorFactory.newEnumGenerator(enumType));
		}
		if (file.getOptions().getJavaGenericServices())
		{
			for (com.google.protobuf.Descriptors.ServiceDescriptor service : file.getServices())
			{
				serviceGenerators.add(generatorFactory.newServiceGenerator(service));
			}
		}
	}

	public boolean validate(Consumer<String> error)
	{
		// TODO: Implement validation
		return true;
	}

	public void generate(PrintWriter printer)
	{
		// Basic generation logic
		printer.println("// Generated by the protocol buffer compiler.  DO NOT EDIT!");
		printer.println("// NO CHECKED-IN PROTOBUF GENCODE");
		printer.println("// source: " + file.getName());
		printer.println("// Protobuf Java Version: 4.33.4");
		printer.println();

		if (!javaPackage.isEmpty())
		{
			printer.println("package " + javaPackage + ";");
			printer.println();
		}

		printer.println("@com.google.protobuf.Generated");
		// Match C++ behavior: extend GeneratedFile when HasDescriptorMethods returns true
		// HasDescriptorMethods(file, enforceLite) returns !enforceLite
		String extendsClause = !context.enforceLite() 
			? " extends com.google.protobuf.GeneratedFile " 
			: "";
		printer.println("public final class " + className + extendsClause + "{");
		printer.println("  private " + className + "() {}");
		printer.println("  static {");
		printer.println("    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(");
		printer.println("      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,");
		printer.println("      /* major= */ 4,");
		printer.println("      /* minor= */ 33,");
		printer.println("      /* patch= */ 4,");
		printer.println("      /* suffix= */ \"\",");
		printer.println("      \"" + className + "\");");
		printer.println("  }");

		// Match C++ format: method signature at 2 spaces, continuation at 6 spaces (4 more), body at 6 spaces, closing brace at 2 spaces
		printer.println("  public static void registerAllExtensions(");
		printer.println("      com.google.protobuf.ExtensionRegistryLite registry) {");
		// Body is indented 4 more spaces (6 total from class start)
		for (ExtensionGenerator generator : extensionGenerators)
		{
			generator.generateRegistrationCode(printer);
		}
		for (MessageGenerator generator : messageGenerators)
		{
			generator.generateExtensionRegistrationCode(printer);
		}
		printer.println("  }");
		printer.println();

		if (!context.enforceLite())
		{
			// Match C++ format: method signature at 2 spaces, continuation at 6 spaces, body at 6 spaces, closing brace at 2 spaces
			printer.println("  public static void registerAllExtensions(");
			printer.println("      com.google.protobuf.ExtensionRegistry registry) {");
			printer.println("    registerAllExtensions(");
			printer.println("        (com.google.protobuf.ExtensionRegistryLite) registry);");
			printer.println("  }");
		}

		// Match C++ order: enums first, then messages, then extensions, then static variables
		// Generate enums (nested in file class) - only top-level enums
		for (int i = 0; i < file.getEnumTypes().size(); i++)
		{
			com.google.protobuf.Descriptors.EnumDescriptor enumType = file.getEnumTypes().get(i);
			// Check if enum is nested in file class (not nested in a message)
			// For now, check if containingType is null (top-level enum)
			if (enumType.getContainingType() == null)
			{
				enumGenerators.get(i).generate(printer);
			}
		}
		
		// Generate messages (nested in file class) - only top-level messages
		for (int i = 0; i < file.getMessageTypes().size(); i++)
		{
			com.google.protobuf.Descriptors.Descriptor messageType = file.getMessageTypes().get(i);
			// Check if message is nested in file class (not nested in another message)
			if (messageType.getContainingType() == null)
			{
				
				messageGenerators.get(i).generateInterface(printer);
				messageGenerators.get(i).generate(printer);
				
			}
		}

		// Generate services
		for (ServiceGenerator generator : serviceGenerators)
		{
			generator.generate(printer);
		}
		
		// Generate extensions (must be in outer class)
		for (ExtensionGenerator generator : extensionGenerators)
		{
			generator.generate(printer);
		}
		
		// Generate static variables after messages/extensions (match C++ order)
		int[] bytecodeEstimate = new int[] { 0 };
		for (MessageGenerator generator : messageGenerators)
		{
			generator.generateStaticVariables(printer, bytecodeEstimate);
		}

		// Descriptor Initialization
		printer.println();
		printer.println("  public static com.google.protobuf.Descriptors.FileDescriptor");
		printer.println("      getDescriptor() {");
		printer.println("    return descriptor;");
		printer.println("  }");
		printer.println("  private static  com.google.protobuf.Descriptors.FileDescriptor");
		printer.println("      descriptor;");
		printer.println("  static {");
		SharedCodeGenerator sharedCodeGenerator = new SharedCodeGenerator(file, sourceProto, options);
		sharedCodeGenerator.generateDescriptors(printer);

		// Internal init
		for (MessageGenerator generator : messageGenerators)
		{
			generator.generateStaticVariableInitializers(printer);
		}
		for (ExtensionGenerator generator : extensionGenerators)
		{
			generator.generateNonNestedInitializationCode(printer);
		}

		printer.println("    descriptor.resolveAllFeaturesImmutable();");
		for (FileDescriptor dependency : file.getDependencies())
		{
			printer.println("    " + nameResolver.getImmutableClassName(dependency) + ".getDescriptor();");
		}
		printer.println("  }");
		printer.println();
		printer.println("  // @@protoc_insertion_point(outer_class_scope)");
		printer.print("}");
	}

	public String getClassName()
	{
		return className;
	}

	public String getJavaPackage()
	{
		return javaPackage;
	}

	public void generateSiblings(String packageDir, GeneratorContext generatorContext, List<String> fileList,
			List<String> annotationList)
	{
		// TODO: Implement siblings generation
	}
}
