package com.google.protobuf.compiler.java;

import com.google.protobuf.Descriptors.FileDescriptor;
import com.google.protobuf.compiler.GeneratorContext;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

public class FileGenerator {
  private final FileDescriptor file;
  private final Options options;
  private final boolean immutableApi;
  private final Context context;
  private final ClassNameResolver nameResolver;
  private final GeneratorFactory generatorFactory;
  private final String className;
  private final String javaPackage;

  private final List<MessageGenerator> messageGenerators = new ArrayList<>();
  private final List<ExtensionGenerator> extensionGenerators = new ArrayList<>();

  public FileGenerator(FileDescriptor file, Options options, boolean immutableApi) {
    this.file = file;
    this.options = options;
    this.immutableApi = immutableApi;
    this.context = new Context(file, options);
    this.nameResolver = context.getNameResolver();
    this.className = nameResolver.getFileClassName(file, immutableApi);
    this.javaPackage = nameResolver.getFileJavaPackage(file);

    // TODO: Choose factory based on lite/full
    if (context.enforceLite()) {
      throw new UnsupportedOperationException("Lite generation not yet implemented");
    } else {
      this.generatorFactory = new com.google.protobuf.compiler.java.full.GeneratorFactory(context);
    }

    for (com.google.protobuf.Descriptors.Descriptor messageType : file.getMessageTypes()) {
      messageGenerators.add(generatorFactory.newMessageGenerator(messageType));
    }
    for (com.google.protobuf.Descriptors.FieldDescriptor extension : file.getExtensions()) {
      extensionGenerators.add(generatorFactory.newExtensionGenerator(extension));
    }
  }

  public boolean validate(Consumer<String> error) {
      // TODO: Implement validation
      return true;
  }

  public void generate(PrintWriter printer) {
      // Basic generation logic
      printer.println("// Generated by the protocol buffer compiler.  DO NOT EDIT!");
      printer.println("// source: " + file.getName());
      printer.println();

      if (!javaPackage.isEmpty()) {
          printer.println("package " + javaPackage + ";");
          printer.println();
      }

      printer.println("public final class " + className + " {");
      printer.println("  private " + className + "() {}");

      // ... call generators
      for (MessageGenerator generator : messageGenerators) {
          generator.generate(printer);
      }
      for (ExtensionGenerator generator : extensionGenerators) {
          generator.generate(printer);
      }

      printer.println("}");
  }

  public String getClassName() {
      return className;
  }

  public String getJavaPackage() {
      return javaPackage;
  }

  public void generateSiblings(String packageDir, GeneratorContext generatorContext, List<String> fileList, List<String> annotationList) {
      // TODO: Implement siblings generation
  }
}
